using System;
using System.Linq;
using MongoDB.Driver;
using Resources;

namespace DataLoader
{
    class Program
    {
        // ReSharper disable UnusedParameter.Local
        static void Main(string[] args)
        // ReSharper restore UnusedParameter.Local
        {
            var server = MongoServer.Create("mongodb://steve.hebert:grandam@vincent.mongohq.com:10062/openlocker_db");
            //var server = MongoServer.Create("mongodb://localhost:27017/");
            server.CreateDatabaseSettings("openlocker_db");

            var database = server.GetDatabase("openlocker_db");
            //database.CreateCollection(typeof (BidDetail).Name);
            //database.CreateCollection(typeof(Player).Name);
            //database.DropCollection(typeof (BidDetail).Name);

            var collection = database.GetCollection<Player>(typeof(Player).Name);

            foreach (var player in collection.FindAll().AsEnumerable())
                Console.Write(player);

            collection.RemoveAll();

            collection.Insert(new Player {Id = 1, Name = "Foster, Arian", Position= "RB", Team="HOU"});
collection.Insert(new Player {Id = 2, Name = "Rice, Ray", Position= "RB", Team="BAL"});
collection.Insert(new Player {Id = 3, Name = "McCoy, LeSean", Position= "RB", Team="PHI"});
collection.Insert(new Player {Id = 4, Name = "Rodgers, Aaron", Position= "QB", Team="GB"});
collection.Insert(new Player {Id = 5, Name = "Johnson, Calvin", Position= "WR", Team="DET"});
collection.Insert(new Player {Id = 6, Name = "Johnson, Chris", Position= "RB", Team="TEN"});
collection.Insert(new Player {Id = 7, Name = "Brady, Tom", Position= "QB", Team="NE"});
collection.Insert(new Player {Id = 8, Name = "Brees, Drew", Position= "QB", Team="NO"});
collection.Insert(new Player {Id = 9, Name = "Fitzgerald, Larry", Position= "WR", Team="ARI"});
collection.Insert(new Player {Id = 10, Name = "Stafford, Matthew", Position= "QB", Team="DET"});
collection.Insert(new Player {Id = 11, Name = "Forte, Matt", Position= "RB", Team="CHI"});
collection.Insert(new Player {Id = 12, Name = "Jones-Drew, Maurice", Position= "RB", Team="JAC"});
collection.Insert(new Player {Id = 13, Name = "Johnson, Andre", Position= "WR", Team="HOU"});
collection.Insert(new Player {Id = 14, Name = "McFadden, Darren", Position= "RB", Team="OAK"});
collection.Insert(new Player {Id = 15, Name = "White, Roddy", Position= "WR", Team="ATL"});
collection.Insert(new Player {Id = 16, Name = "Gronkowski, Rob", Position= "TE", Team="NE"});
collection.Insert(new Player {Id = 17, Name = "Murray, DeMarco", Position= "RB", Team="DAL"});
collection.Insert(new Player {Id = 18, Name = "Newton, Cam", Position= "QB", Team="CAR"});
collection.Insert(new Player {Id = 19, Name = "Welker, Wes", Position= "WR", Team="NE"});
collection.Insert(new Player {Id = 20, Name = "Jennings, Greg", Position= "WR", Team="GB"});
collection.Insert(new Player {Id = 21, Name = "Charles, Jamaal", Position= "RB", Team="KC"});
collection.Insert(new Player {Id = 22, Name = "Jones, Julio", Position= "WR", Team="ATL"});
collection.Insert(new Player {Id = 23, Name = "Green, A.J.", Position= "WR", Team="CIN"});
collection.Insert(new Player {Id = 24, Name = "Lynch, Marshawn", Position= "RB", Team="SEA"});
collection.Insert(new Player {Id = 25, Name = "Graham, Jimmy", Position= "TE", Team="NO"});
collection.Insert(new Player {Id = 26, Name = "Mathews, Ryan", Position= "RB", Team="SD"});
collection.Insert(new Player {Id = 27, Name = "Nicks, Hakeem", Position= "WR", Team="NYG"});
collection.Insert(new Player {Id = 28, Name = "Peterson, Adrian", Position= "RB", Team="MIN"});
collection.Insert(new Player {Id = 29, Name = "Wallace, Mike", Position= "WR", Team="PIT"});
collection.Insert(new Player {Id = 30, Name = "Jackson, Steven", Position= "RB", Team="STL"});
collection.Insert(new Player {Id = 31, Name = "Cruz, Victor", Position= "WR", Team="NYG"});
collection.Insert(new Player {Id = 32, Name = "Vick, Michael", Position= "QB", Team="PHI"});
collection.Insert(new Player {Id = 33, Name = "Richardson, Trent", Position= "RB", Team="CLE"});
collection.Insert(new Player {Id = 34, Name = "Jackson, Fred", Position= "RB", Team="BUF"});
collection.Insert(new Player {Id = 35, Name = "Marshall, Brandon", Position= "WR", Team="CHI"});
collection.Insert(new Player {Id = 36, Name = "Manning, Eli", Position= "QB", Team="NYG"});
collection.Insert(new Player {Id = 37, Name = "Smith, Steve", Position= "WR", Team="CAR"});
collection.Insert(new Player {Id = 38, Name = "Nelson, Jordy", Position= "WR", Team="GB"});
collection.Insert(new Player {Id = 39, Name = "Turner, Michael", Position= "RB", Team="ATL"});
collection.Insert(new Player {Id = 40, Name = "Bryant, Dez", Position= "WR", Team="DAL"});
collection.Insert(new Player {Id = 41, Name = "Romo, Tony", Position= "QB", Team="DAL"});
collection.Insert(new Player {Id = 42, Name = "Bradshaw, Ahmad", Position= "RB", Team="NYG"});
collection.Insert(new Player {Id = 43, Name = "Gore, Frank", Position= "RB", Team="SF"});
collection.Insert(new Player {Id = 44, Name = "Sproles, Darren", Position= "RB", Team="NO"});
collection.Insert(new Player {Id = 45, Name = "Colston, Marques", Position= "WR", Team="NO"});
collection.Insert(new Player {Id = 46, Name = "Harvin, Percy", Position= "WR", Team="MIN"});
collection.Insert(new Player {Id = 47, Name = "Lloyd, Brandon", Position= "WR", Team="NE"});
collection.Insert(new Player {Id = 48, Name = "Jackson, Vincent", Position= "WR", Team="TB"});
collection.Insert(new Player {Id = 49, Name = "Bush, Reggie", Position= "RB", Team="MIA"});
collection.Insert(new Player {Id = 50, Name = "Manning, Peyton", Position= "QB", Team="DEN"});
collection.Insert(new Player {Id = 51, Name = "Martin, Doug", Position= "RB", Team="TB"});
collection.Insert(new Player {Id = 52, Name = "Thomas, Demaryius", Position= "WR", Team="DEN"});
collection.Insert(new Player {Id = 53, Name = "Rivers, Philip", Position= "QB", Team="SD"});
collection.Insert(new Player {Id = 54, Name = "Austin, Miles", Position= "WR", Team="DAL"});
collection.Insert(new Player {Id = 55, Name = "Bowe, Dwayne", Position= "WR", Team="KC"});
collection.Insert(new Player {Id = 56, Name = "Maclin, Jeremy", Position= "WR", Team="PHI"});
collection.Insert(new Player {Id = 57, Name = "Green-Ellis, BenJarvus", Position= "RB", Team="CIN"});
collection.Insert(new Player {Id = 58, Name = "Gates, Antonio", Position= "TE", Team="SD"});
collection.Insert(new Player {Id = 59, Name = "Ryan, Matt", Position= "QB", Team="ATL"});
collection.Insert(new Player {Id = 60, Name = "Decker, Eric", Position= "WR", Team="DEN"});
collection.Insert(new Player {Id = 61, Name = "McGahee, Willis", Position= "RB", Team="DEN"});
collection.Insert(new Player {Id = 62, Name = "Finley, Jermichael", Position= "TE", Team="GB"});
collection.Insert(new Player {Id = 63, Name = "Johnson, Steve", Position= "WR", Team="BUF"});
collection.Insert(new Player {Id = 64, Name = "Greene, Shonn", Position= "RB", Team="NYJ"});
collection.Insert(new Player {Id = 65, Name = "Wells (Beanie), Chris", Position= "RB", Team="ARI"});
collection.Insert(new Player {Id = 66, Name = "Hernandez, Aaron", Position= "TE", Team="NE"});
collection.Insert(new Player {Id = 67, Name = "Davis, Vernon", Position= "TE", Team="SF"});
collection.Insert(new Player {Id = 68, Name = "Brown, Antonio", Position= "WR", Team="PIT"});
collection.Insert(new Player {Id = 69, Name = "Stewart, Jonathan", Position= "RB", Team="CAR"});
collection.Insert(new Player {Id = 70, Name = "Jackson, DeSean", Position= "WR", Team="PHI"});
collection.Insert(new Player {Id = 71, Name = "Roethlisberger, Ben", Position= "QB", Team="PIT"});
collection.Insert(new Player {Id = 72, Name = "Ridley, Stevan", Position= "RB", Team="NE"});
collection.Insert(new Player {Id = 73, Name = "Meachem, Robert", Position= "WR", Team="SD"});
collection.Insert(new Player {Id = 74, Name = "Britt, Kenny", Position= "WR", Team="TEN"});
collection.Insert(new Player {Id = 75, Name = "Smith, Torrey", Position= "WR", Team="BAL"});
collection.Insert(new Player {Id = 76, Name = "Griffin III, Robert", Position= "QB", Team="WAS"});
collection.Insert(new Player {Id = 77, Name = "Davis, Fred", Position= "TE", Team="WAS"});
collection.Insert(new Player {Id = 78, Name = "Williams, DeAngelo", Position= "RB", Team="CAR"});
collection.Insert(new Player {Id = 79, Name = "Spiller, C.J.", Position= "RB", Team="BUF"});
collection.Insert(new Player {Id = 80, Name = "Schaub, Matt", Position= "QB", Team="HOU"});
collection.Insert(new Player {Id = 81, Name = "Hillis, Peyton", Position= "RB", Team="KC"});
collection.Insert(new Player {Id = 82, Name = "Garcon, Pierre", Position= "WR", Team="WAS"});
collection.Insert(new Player {Id = 83, Name = "Helu, Roy", Position= "RB", Team="WAS"});
collection.Insert(new Player {Id = 84, Name = "Redman, Isaac", Position= "RB", Team="PIT"});
collection.Insert(new Player {Id = 85, Name = "Tate, Ben", Position= "RB", Team="HOU"});
collection.Insert(new Player {Id = 86, Name = "Witten, Jason", Position= "TE", Team="DAL"});
collection.Insert(new Player {Id = 87, Name = "Ingram, Mark", Position= "RB", Team="NO"});
collection.Insert(new Player {Id = 88, Name = "Smith, Kevin", Position= "RB", Team="DET"});
collection.Insert(new Player {Id = 89, Name = "Bush, Michael", Position= "RB", Team="CHI"});
collection.Insert(new Player {Id = 90, Name = "Cutler, Jay", Position= "QB", Team="CHI"});
collection.Insert(new Player {Id = 91, Name = "Wayne, Reggie", Position= "WR", Team="IND"});
collection.Insert(new Player {Id = 92, Name = "Brown, Donald", Position= "RB", Team="IND"});
collection.Insert(new Player {Id = 93, Name = "Benson, Cedric", Position= "RB", Team="GB"});
collection.Insert(new Player {Id = 94, Name = "Gerhart, Toby", Position= "RB", Team="MIN"});
collection.Insert(new Player {Id = 95, Name = "Gonzalez, Tony", Position= "TE", Team="ATL"});
collection.Insert(new Player {Id = 96, Name = "Moore, Denarius", Position= "WR", Team="OAK"});
collection.Insert(new Player {Id = 97, Name = "Dalton, Andy", Position= "QB", Team="CIN"});
collection.Insert(new Player {Id = 98, Name = "Freeman, Josh", Position= "QB", Team="TB"});
collection.Insert(new Player {Id = 99, Name = "Boldin, Anquan", Position= "WR", Team="BAL"});
collection.Insert(new Player {Id = 100, Name = "Pettigrew, Brandon", Position= "TE", Team="DET"});
collection.Insert(new Player {Id = 101, Name = "Tamme, Jacob", Position= "TE", Team="DEN"});
collection.Insert(new Player {Id = 102, Name = "Leshoure, Mikel", Position= "RB", Team="DET"});
collection.Insert(new Player {Id = 103, Name = "Starks, James", Position= "RB", Team="GB"});
collection.Insert(new Player {Id = 104, Name = "San Francisco 49ers", Position= "DEF", Team="SF"});
collection.Insert(new Player {Id = 105, Name = "Luck, Andrew", Position= "QB", Team="IND"});
collection.Insert(new Player {Id = 106, Name = "Holmes, Santonio", Position= "WR", Team="NYJ"});
collection.Insert(new Player {Id = 107, Name = "Wilson, David", Position= "RB", Team="NYG"});
collection.Insert(new Player {Id = 108, Name = "Young, Titus", Position= "WR", Team="DET"});
collection.Insert(new Player {Id = 109, Name = "Heyward-Bey, Darrius", Position= "WR", Team="OAK"});
collection.Insert(new Player {Id = 110, Name = "Blackmon, Justin", Position= "WR", Team="JAC"});
collection.Insert(new Player {Id = 111, Name = "Floyd, Malcom", Position= "WR", Team="SD"});
collection.Insert(new Player {Id = 112, Name = "Moore, Lance", Position= "WR", Team="NO"});
collection.Insert(new Player {Id = 113, Name = "Little, Greg", Position= "WR", Team="CLE"});
collection.Insert(new Player {Id = 114, Name = "Williams, Ryan", Position= "RB", Team="ARI"});
collection.Insert(new Player {Id = 115, Name = "Flacco, Joe", Position= "QB", Team="BAL"});
collection.Insert(new Player {Id = 116, Name = "Kolb, Kevin", Position= "QB", Team="ARI"});
collection.Insert(new Player {Id = 117, Name = "Washington, Nate", Position= "WR", Team="TEN"});
collection.Insert(new Player {Id = 118, Name = "Crabtree, Michael", Position= "WR", Team="SF"});
collection.Insert(new Player {Id = 119, Name = "Celek, Brent", Position= "TE", Team="PHI"});
collection.Insert(new Player {Id = 120, Name = "Robinson, Laurent", Position= "WR", Team="JAC"});
collection.Insert(new Player {Id = 121, Name = "Williams, Mike", Position= "WR", Team="TB"});
collection.Insert(new Player {Id = 122, Name = "Thomas, Pierre", Position= "RB", Team="NO"});
collection.Insert(new Player {Id = 123, Name = "Palmer, Carson", Position= "QB", Team="OAK"});
collection.Insert(new Player {Id = 124, Name = "Blount, LeGarrette", Position= "RB", Team="TB"});
collection.Insert(new Player {Id = 125, Name = "Bradford, Sam", Position= "QB", Team="STL"});
collection.Insert(new Player {Id = 126, Name = "Fitzpatrick, Ryan", Position= "QB", Team="BUF"});
collection.Insert(new Player {Id = 127, Name = "Rice, Sidney", Position= "WR", Team="SEA"});
collection.Insert(new Player {Id = 128, Name = "Manningham, Mario", Position= "WR", Team="SF"});
collection.Insert(new Player {Id = 129, Name = "Vereen, Shane", Position= "RB", Team="NE"});
collection.Insert(new Player {Id = 130, Name = "Locker, Jake", Position= "QB", Team="TEN"});
collection.Insert(new Player {Id = 131, Name = "Keller, Dustin", Position= "TE", Team="NYJ"});
collection.Insert(new Player {Id = 132, Name = "Jennings, Rashad", Position= "RB", Team="JAC"});
collection.Insert(new Player {Id = 133, Name = "Morris, Alfred", Position= "RB", Team="WAS"});
collection.Insert(new Player {Id = 134, Name = "Mendenhall, Rashard", Position= "RB", Team="PIT"});
collection.Insert(new Player {Id = 135, Name = "Jones, Felix", Position= "RB", Team="DAL"});
collection.Insert(new Player {Id = 136, Name = "Smith, Alex", Position= "QB", Team="SF"});
collection.Insert(new Player {Id = 137, Name = "Baldwin, Doug", Position= "WR", Team="SEA"});
collection.Insert(new Player {Id = 138, Name = "Cook, Jared", Position= "TE", Team="TEN"});
collection.Insert(new Player {Id = 139, Name = "Gresham, Jermaine", Position= "TE", Team="CIN"});
collection.Insert(new Player {Id = 140, Name = "Collie, Austin", Position= "WR", Team="IND"});
collection.Insert(new Player {Id = 141, Name = "Winslow, Kellen", Position= "TE", Team="FA"});
collection.Insert(new Player {Id = 142, Name = "Cassel, Matt", Position= "QB", Team="KC"});
collection.Insert(new Player {Id = 143, Name = "Thomas, Daniel", Position= "RB", Team="MIA"});
collection.Insert(new Player {Id = 144, Name = "Daniels, Owen", Position= "TE", Team="HOU"});
collection.Insert(new Player {Id = 145, Name = "Brown, Vincent", Position= "WR", Team="SD"});
collection.Insert(new Player {Id = 146, Name = "Fleener, Coby", Position= "TE", Team="IND"});
collection.Insert(new Player {Id = 147, Name = "New York Jets", Position= "DEF", Team="NYJ"});
collection.Insert(new Player {Id = 148, Name = "Best, Jahvid", Position= "RB", Team="DET"});
collection.Insert(new Player {Id = 149, Name = "Royster, Evan", Position= "RB", Team="WAS"});
collection.Insert(new Player {Id = 150, Name = "Owens, Terrell", Position= "WR", Team="FA"});
collection.Insert(new Player {Id = 151, Name = "Baltimore Ravens", Position= "DEF", Team="BAL"});
collection.Insert(new Player {Id = 152, Name = "Flynn, Matt", Position= "QB", Team="SEA"});
collection.Insert(new Player {Id = 153, Name = "Houston Texans", Position= "DEF", Team="HOU"});
collection.Insert(new Player {Id = 154, Name = "Hillman, Ronnie", Position= "RB", Team="DEN"});
collection.Insert(new Player {Id = 155, Name = "Janikowski, Sebastian", Position= "K", Team="OAK"});
collection.Insert(new Player {Id = 156, Name = "Green Bay Packers", Position= "DEF", Team="GB"});
collection.Insert(new Player {Id = 157, Name = "Rudolph, Kyle", Position= "TE", Team="MIN"});
collection.Insert(new Player {Id = 158, Name = "Akers, David", Position= "K", Team="SF"});
collection.Insert(new Player {Id = 159, Name = "Baldwin, Jon", Position= "WR", Team="KC"});
collection.Insert(new Player {Id = 160, Name = "Philadelphia Eagles", Position= "DEF", Team="PHI"});
collection.Insert(new Player {Id = 161, Name = "Detroit Lions", Position= "DEF", Team="DET"});
collection.Insert(new Player {Id = 162, Name = "Amendola, Danny", Position= "WR", Team="STL"});
collection.Insert(new Player {Id = 163, Name = "Gostkowski, Stephen", Position= "K", Team="NE"});
collection.Insert(new Player {Id = 164, Name = "Chicago Bears", Position= "DEF", Team="CHI"});
collection.Insert(new Player {Id = 165, Name = "Moss, Santana", Position= "WR", Team="WAS"});
collection.Insert(new Player {Id = 166, Name = "Brown, Ronnie", Position= "RB", Team="SD"});
collection.Insert(new Player {Id = 167, Name = "Pittsburgh Steelers", Position= "DEF", Team="PIT"});
collection.Insert(new Player {Id = 168, Name = "Scott, Bernard", Position= "RB", Team="CIN"});
collection.Insert(new Player {Id = 169, Name = "Randle, Reuben", Position= "WR", Team="NYG"});
collection.Insert(new Player {Id = 170, Name = "Wright, Kendall", Position= "WR", Team="TEN"});
collection.Insert(new Player {Id = 171, Name = "Tolbert, Mike", Position= "RB", Team="CAR"});
collection.Insert(new Player {Id = 172, Name = "Hankerson, Leonard", Position= "WR", Team="WAS"});
collection.Insert(new Player {Id = 173, Name = "New England Patriots", Position= "DEF", Team="NE"});
collection.Insert(new Player {Id = 174, Name = "Cobb, Randall", Position= "WR", Team="GB"});
collection.Insert(new Player {Id = 175, Name = "Rodgers, Jacquizz", Position= "RB", Team="ATL"});
collection.Insert(new Player {Id = 176, Name = "Doucet, Early", Position= "WR", Team="ARI"});
collection.Insert(new Player {Id = 177, Name = "Bailey, Dan", Position= "K", Team="DAL"});
collection.Insert(new Player {Id = 178, Name = "Pead, Isaiah", Position= "RB", Team="STL"});
collection.Insert(new Player {Id = 179, Name = "Goodson, Mike", Position= "RB", Team="OAK"});
collection.Insert(new Player {Id = 180, Name = "Burleson, Nate", Position= "WR", Team="DET"});
collection.Insert(new Player {Id = 181, Name = "LaFell, Brandon", Position= "WR", Team="CAR"});
collection.Insert(new Player {Id = 182, Name = "Sanchez, Mark", Position= "QB", Team="NYJ"});
collection.Insert(new Player {Id = 183, Name = "Moss, Randy", Position= "WR", Team="SF"});
collection.Insert(new Player {Id = 184, Name = "Carter, Delone", Position= "RB", Team="IND"});
collection.Insert(new Player {Id = 185, Name = "Quick, Brian", Position= "WR", Team="STL"});
collection.Insert(new Player {Id = 186, Name = "Hunter, Kendall", Position= "RB", Team="SF"});
collection.Insert(new Player {Id = 187, Name = "Crosby, Mason", Position= "K", Team="GB"});
collection.Insert(new Player {Id = 188, Name = "Seattle Seahawks", Position= "DEF", Team="SEA"});
collection.Insert(new Player {Id = 189, Name = "Jones, James", Position= "WR", Team="GB"});
collection.Insert(new Player {Id = 190, Name = "Floyd, Michael", Position= "WR", Team="ARI"});
collection.Insert(new Player {Id = 191, Name = "New York Giants", Position= "DEF", Team="NYG"});
collection.Insert(new Player {Id = 192, Name = "Henne, Chad", Position= "QB", Team="JAC"});
collection.Insert(new Player {Id = 193, Name = "Webb, Joe", Position= "QB", Team="MIN"});
collection.Insert(new Player {Id = 194, Name = "Massaquoi, Mohamed", Position= "WR", Team="CLE"});
collection.Insert(new Player {Id = 195, Name = "Grossman, Rex", Position= "QB", Team="WAS"});
collection.Insert(new Player {Id = 196, Name = "Green, Alex", Position= "RB", Team="GB"});
collection.Insert(new Player {Id = 197, Name = "Tannehill, Ryan", Position= "QB", Team="MIA"});
collection.Insert(new Player {Id = 198, Name = "Douglas, Harry", Position= "WR", Team="ATL"});
collection.Insert(new Player {Id = 199, Name = "Benn, Arrelious", Position= "WR", Team="TB"});
collection.Insert(new Player {Id = 200, Name = "Gibson, Brandon", Position= "WR", Team="STL"});
collection.Insert(new Player {Id = 201, Name = "Jacobs, Brandon", Position= "RB", Team="SF"});
collection.Insert(new Player {Id = 202, Name = "Brinkley, Curtis", Position= "RB", Team="SD"});
collection.Insert(new Player {Id = 203, Name = "Hasselbeck, Matt", Position= "QB", Team="TEN"});
collection.Insert(new Player {Id = 204, Name = "Heap, Todd", Position= "TE", Team="ARI"});
collection.Insert(new Player {Id = 205, Name = "Avant, Jason", Position= "WR", Team="PHI"});
collection.Insert(new Player {Id = 206, Name = "Scheffler, Tony", Position= "TE", Team="DET"});
collection.Insert(new Player {Id = 207, Name = "Bullock, Randy", Position= "K", Team="HOU"});
collection.Insert(new Player {Id = 208, Name = "Caldwell, Andre", Position= "WR", Team="DEN"});
collection.Insert(new Player {Id = 209, Name = "Kendricks, Lance", Position= "TE", Team="STL"});
collection.Insert(new Player {Id = 210, Name = "Driver, Donald", Position= "WR", Team="GB"});
collection.Insert(new Player {Id = 211, Name = "Jenkins, Michael", Position= "WR", Team="MIN"});
collection.Insert(new Player {Id = 212, Name = "Alexander, Danario", Position= "WR", Team="STL"});
collection.Insert(new Player {Id = 213, Name = "Cribbs, Josh", Position= "WR", Team="CLE"});
collection.Insert(new Player {Id = 214, Name = "Smith, Steve", Position= "WR", Team="STL"});
collection.Insert(new Player {Id = 215, Name = "Sanders, Emmanuel", Position= "WR", Team="PIT"});
collection.Insert(new Player {Id = 216, Name = "Turbin, Robert", Position= "RB", Team="SEA"});
collection.Insert(new Player {Id = 217, Name = "Ford, Jacoby", Position= "WR", Team="OAK"});
collection.Insert(new Player {Id = 218, Name = "Hartley, Garrett", Position= "K", Team="NO"});
collection.Insert(new Player {Id = 219, Name = "Buffalo Bills", Position= "DEF", Team="BUF"});
collection.Insert(new Player {Id = 220, Name = "Prater, Matt", Position= "K", Team="DEN"});
collection.Insert(new Player {Id = 221, Name = "Ponder, Christian", Position= "QB", Team="MIN"});
collection.Insert(new Player {Id = 222, Name = "Powell, Bilal", Position= "RB", Team="NYJ"});
collection.Insert(new Player {Id = 223, Name = "Hardesty, Montario", Position= "RB", Team="CLE"});
collection.Insert(new Player {Id = 224, Name = "Jones, Taiwan", Position= "RB", Team="OAK"});
collection.Insert(new Player {Id = 225, Name = "Jeffery, Alshon", Position= "WR", Team="CHI"});
collection.Insert(new Player {Id = 226, Name = "Bironas, Rob", Position= "K", Team="TEN"});
collection.Insert(new Player {Id = 227, Name = "Gould, Robbie", Position= "K", Team="CHI"});
collection.Insert(new Player {Id = 228, Name = "Henery, Alex", Position= "K", Team="PHI"});
collection.Insert(new Player {Id = 229, Name = "Snelling, Jason", Position= "RB", Team="ATL"});
collection.Insert(new Player {Id = 230, Name = "Atlanta Falcons", Position= "DEF", Team="ATL"});
collection.Insert(new Player {Id = 231, Name = "Bess, Davone", Position= "WR", Team="MIA"});
collection.Insert(new Player {Id = 232, Name = "Weeden, Brandon", Position= "QB", Team="CLE"});
collection.Insert(new Player {Id = 233, Name = "Breaston, Steve", Position= "WR", Team="KC"});
collection.Insert(new Player {Id = 234, Name = "Roberts, Andre", Position= "WR", Team="ARI"});
collection.Insert(new Player {Id = 235, Name = "Henderson, Devery", Position= "WR", Team="NO"});
collection.Insert(new Player {Id = 236, Name = "McKnight, Joe", Position= "RB", Team="NYJ"});
collection.Insert(new Player {Id = 237, Name = "Watson, Benjamin", Position= "TE", Team="CLE"});
collection.Insert(new Player {Id = 238, Name = "Pierce, Bernard", Position= "RB", Team="BAL"});
collection.Insert(new Player {Id = 239, Name = "Hightower, Tim", Position= "RB", Team="FA"});
collection.Insert(new Player {Id = 240, Name = "Kuhn, John", Position= "RB", Team="GB"});
collection.Insert(new Player {Id = 241, Name = "Lewis, Marcedes", Position= "TE", Team="JAC"});
collection.Insert(new Player {Id = 242, Name = "Stephens-Howling, LaRod", Position= "RB", Team="ARI"});
collection.Insert(new Player {Id = 243, Name = "Walter, Kevin", Position= "WR", Team="HOU"});
collection.Insert(new Player {Id = 244, Name = "Nugent, Mike", Position= "K", Team="CIN"});
collection.Insert(new Player {Id = 245, Name = "Reece, Marcel", Position= "RB", Team="OAK"});
collection.Insert(new Player {Id = 246, Name = "Sanu, Mohamed", Position= "WR", Team="CIN"});
collection.Insert(new Player {Id = 247, Name = "Washington, Leon", Position= "RB", Team="SEA"});
collection.Insert(new Player {Id = 248, Name = "Dickson, Ed", Position= "TE", Team="BAL"});
collection.Insert(new Player {Id = 249, Name = "Simpson, Jerome", Position= "WR", Team="MIN"});
collection.Insert(new Player {Id = 250, Name = "Tebow, Tim", Position= "QB", Team="NYJ"});
collection.Insert(new Player {Id = 251, Name = "Kaeding, Nate", Position= "K", Team="SD"});
collection.Insert(new Player {Id = 252, Name = "Bryant, Matt", Position= "K", Team="ATL"});
collection.Insert(new Player {Id = 253, Name = "Hill, Stephen", Position= "WR", Team="NYJ"});
collection.Insert(new Player {Id = 254, Name = "Hanson, Jason", Position= "K", Team="DET"});
collection.Insert(new Player {Id = 255, Name = "Ball, Lance", Position= "RB", Team="DEN"});
collection.Insert(new Player {Id = 256, Name = "Miller, Heath", Position= "TE", Team="PIT"});
collection.Insert(new Player {Id = 257, Name = "Bennett, Martellus", Position= "TE", Team="NYG"});
collection.Insert(new Player {Id = 258, Name = "Ringer, Javon", Position= "RB", Team="TEN"});
collection.Insert(new Player {Id = 259, Name = "Cundiff, Billy", Position= "K", Team="WAS"});
collection.Insert(new Player {Id = 260, Name = "Nelson, David", Position= "WR", Team="BUF"});
collection.Insert(new Player {Id = 261, Name = "Gabbert, Blaine", Position= "QB", Team="JAC"});
collection.Insert(new Player {Id = 262, Name = "Wilson, Russell", Position= "QB", Team="SEA"});
collection.Insert(new Player {Id = 263, Name = "Woodhead, Danny", Position= "RB", Team="NE"});
collection.Insert(new Player {Id = 264, Name = "Dallas Cowboys", Position= "DEF", Team="DAL"});
collection.Insert(new Player {Id = 265, Name = "Tanner, Phillip", Position= "RB", Team="DAL"});
collection.Insert(new Player {Id = 266, Name = "Pitta, Dennis", Position= "TE", Team="BAL"});
collection.Insert(new Player {Id = 267, Name = "Chandler, Scott", Position= "TE", Team="BUF"});
collection.Insert(new Player {Id = 268, Name = "Hartline, Brian", Position= "WR", Team="MIA"});
collection.Insert(new Player {Id = 269, Name = "Skelton, John", Position= "QB", Team="ARI"});
collection.Insert(new Player {Id = 270, Name = "Olsen, Greg", Position= "TE", Team="CAR"});
collection.Insert(new Player {Id = 271, Name = "Fasano, Anthony", Position= "TE", Team="MIA"});
collection.Insert(new Player {Id = 272, Name = "Royal, Eddie", Position= "WR", Team="SD"});
collection.Insert(new Player {Id = 273, Name = "Kansas City Chiefs", Position= "DEF", Team="KC"});
collection.Insert(new Player {Id = 274, Name = "Morgan, Josh", Position= "WR", Team="WAS"});
collection.Insert(new Player {Id = 275, Name = "Harper, Jamie", Position= "RB", Team="TEN"});
collection.Insert(new Player {Id = 276, Name = "Gordon, Josh", Position= "WR", Team="CLE"});
collection.Insert(new Player {Id = 277, Name = "Moeaki, Tony", Position= "TE", Team="KC"});
collection.Insert(new Player {Id = 278, Name = "Armstrong, Anthony", Position= "WR", Team="MIA"});
collection.Insert(new Player {Id = 279, Name = "Dwyer, Jonathan", Position= "RB", Team="PIT"});
collection.Insert(new Player {Id = 280, Name = "Jernigan, Jerrel", Position= "WR", Team="NYG"});
collection.Insert(new Player {Id = 281, Name = "Williams, Damian", Position= "WR", Team="TEN"});
collection.Insert(new Player {Id = 282, Name = "Moore, Evan", Position= "TE", Team="SEA"});
collection.Insert(new Player {Id = 283, Name = "Miller, Lamar", Position= "RB", Team="MIA"});
collection.Insert(new Player {Id = 284, Name = "McClain, Le'Ron", Position= "RB", Team="SD"});
collection.Insert(new Player {Id = 285, Name = "Ogbonnaya, Chris", Position= "RB", Team="CLE"});
collection.Insert(new Player {Id = 286, Name = "Batch, Baron", Position= "RB", Team="PIT"});
collection.Insert(new Player {Id = 287, Name = "Moore, Mewelde", Position= "RB", Team="IND"});
collection.Insert(new Player {Id = 288, Name = "Jackson, Brandon", Position= "RB", Team="CLE"});
collection.Insert(new Player {Id = 289, Name = "Tate, Golden", Position= "WR", Team="SEA"});
collection.Insert(new Player {Id = 290, Name = "Smith, Michael", Position= "RB", Team="TB"});
collection.Insert(new Player {Id = 291, Name = "Ivory, Christopher", Position= "RB", Team="NO"});
collection.Insert(new Player {Id = 292, Name = "Leonard, Brian", Position= "RB", Team="CIN"});
collection.Insert(new Player {Id = 293, Name = "Thomas, Mike", Position= "WR", Team="JAC"});
collection.Insert(new Player {Id = 294, Name = "Brown, Bryce", Position= "RB", Team="PHI"});
collection.Insert(new Player {Id = 295, Name = "Davis, Kellen", Position= "TE", Team="CHI"});
collection.Insert(new Player {Id = 296, Name = "Ware, Danny", Position= "RB", Team="TB"});
collection.Insert(new Player {Id = 297, Name = "Choice, Tashard", Position= "RB", Team="BUF"});
collection.Insert(new Player {Id = 298, Name = "Broyles, Ryan", Position= "WR", Team="DET"});
collection.Insert(new Player {Id = 299, Name = "Lewis, Dion", Position= "RB", Team="PHI"});
collection.Insert(new Player {Id = 300, Name = "Ballard, Vick", Position= "RB", Team="IND"});
collection.Insert(new Player {Id = 301, Name = "Miller, Zach", Position= "TE", Team="SEA"});
collection.Insert(new Player {Id = 302, Name = "Binns, Armon", Position= "WR", Team="CIN"});
collection.Insert(new Player {Id = 303, Name = "Moreno, Knowshon", Position= "RB", Team="DEN"});
collection.Insert(new Player {Id = 304, Name = "James, LaMichael", Position= "RB", Team="SF"});
collection.Insert(new Player {Id = 305, Name = "Edwards, Braylon", Position= "WR", Team="SEA"});
collection.Insert(new Player {Id = 306, Name = "Schilens, Chaz", Position= "WR", Team="NYJ"});
collection.Insert(new Player {Id = 307, Name = "Avery, Donnie", Position= "WR", Team="IND"});
collection.Insert(new Player {Id = 308, Name = "Saine, Brandon", Position= "RB", Team="GB"});
collection.Insert(new Player {Id = 309, Name = "Bennett, Earl", Position= "WR", Team="CHI"});
collection.Insert(new Player {Id = 310, Name = "Givens, Chris", Position= "WR", Team="STL"});
collection.Insert(new Player {Id = 311, Name = "Rainey, Bobby", Position= "RB", Team="BAL"});
collection.Insert(new Player {Id = 312, Name = "Graham, Shayne", Position= "K", Team="HOU"});
collection.Insert(new Player {Id = 313, Name = "Salas, Greg", Position= "WR", Team="NE"});
collection.Insert(new Player {Id = 314, Name = "McCluster, Dexter", Position= "WR", Team="KC"});
collection.Insert(new Player {Id = 315, Name = "Tucker, Justin", Position= "K", Team="BAL"});
collection.Insert(new Player {Id = 316, Name = "Naanee, Legedu", Position= "WR", Team="MIA"});
collection.Insert(new Player {Id = 317, Name = "Richardson, Daryl", Position= "RB", Team="STL"});
collection.Insert(new Player {Id = 318, Name = "Carpenter, Dan", Position= "K", Team="MIA"});
collection.Insert(new Player {Id = 319, Name = "Forsett, Justin", Position= "RB", Team="HOU"});
collection.Insert(new Player {Id = 320, Name = "Stokley, Brandon", Position= "WR", Team="DEN"});
collection.Insert(new Player {Id = 321, Name = "Dreessen, Joel", Position= "TE", Team="DEN"});
collection.Insert(new Player {Id = 322, Name = "Jones, Donald", Position= "WR", Team="BUF"});
collection.Insert(new Player {Id = 323, Name = "Williams, Keiland", Position= "RB", Team="DET"});
collection.Insert(new Player {Id = 324, Name = "Arizona Cardinals", Position= "DEF", Team="ARI"});
collection.Insert(new Player {Id = 325, Name = "Jones, Jacoby", Position= "WR", Team="BAL"});
collection.Insert(new Player {Id = 326, Name = "Rainey, Chris", Position= "RB", Team="PIT"});
            collection.Insert(new Player {Id = 327, Name = "Minnesota Vikings", Position = "DEF", Team = "MIN"});


            
            var collection2 = database.GetCollection<Auction>(typeof(Auction).Name);
            collection2.RemoveAll();
            collection2.Insert(new Auction { Id = 1, Name = "EastSide" });

            var collection3 = database.GetCollection<Owner>(typeof(Owner).Name);
            collection3.RemoveAll();
            collection3.Insert(new Owner { AuctionId = 1, Id = 1, Name = "Sponge Bobs - Bob Gross" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 2, Name = "Prom Queens - Steve Hebert" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 3, Name = "Terminators - Dave Houghton" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 4, Name = "D-Jabs - Bill Benert" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 5, Name = "No More Scum - Tom Houghton" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 6, Name = "Spill Kings - Dave Timm" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 7, Name = "Sodbusters - Larry Fitzpatrick" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 8, Name = "Superstars - Steve Sheahan" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 9, Name = "Wolfpack - Wally Kelsey" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 10, Name = "Zephyrs - Erik Metling" });

            var collection4 = database.GetCollection<Ranking>(typeof(Ranking).Name);
            collection4.RemoveAll();
            collection4.Insert(new Ranking { Id = 1, Name = "Fanball - 10 player" });

            var collection5 = database.GetCollection<RankingDetail>(typeof(RankingDetail).Name);
            collection5.RemoveAll();
            collection5.Insert(new RankingDetail { Id = 1, RankingId = 1, PlayerId = 1, Estimate = 46, Rank = 1 });
collection5.Insert(new RankingDetail { Id = 2, RankingId = 1, PlayerId = 2, Estimate = 45, Rank = 3 });
collection5.Insert(new RankingDetail { Id = 3, RankingId = 1, PlayerId = 3, Estimate = 44, Rank = 4 });
collection5.Insert(new RankingDetail { Id = 4, RankingId = 1, PlayerId = 4, Estimate = 43, Rank = 2 });
collection5.Insert(new RankingDetail { Id = 5, RankingId = 1, PlayerId = 5, Estimate = 42, Rank = 6 });
collection5.Insert(new RankingDetail { Id = 6, RankingId = 1, PlayerId = 6, Estimate = 37, Rank = 8 });
collection5.Insert(new RankingDetail { Id = 7, RankingId = 1, PlayerId = 7, Estimate = 34, Rank = 5 });
collection5.Insert(new RankingDetail { Id = 8, RankingId = 1, PlayerId = 8, Estimate = 36, Rank = 7 });
collection5.Insert(new RankingDetail { Id = 9, RankingId = 1, PlayerId = 9, Estimate = 30, Rank = 15 });
collection5.Insert(new RankingDetail { Id = 10, RankingId = 1, PlayerId = 10, Estimate = 31, Rank = 10 });
collection5.Insert(new RankingDetail { Id = 11, RankingId = 1, PlayerId = 11, Estimate = 36, Rank = 12 });
collection5.Insert(new RankingDetail { Id = 12, RankingId = 1, PlayerId = 12, Estimate = 35, Rank = 17 });
collection5.Insert(new RankingDetail { Id = 13, RankingId = 1, PlayerId = 13, Estimate = 24, Rank = 20 });
collection5.Insert(new RankingDetail { Id = 14, RankingId = 1, PlayerId = 14, Estimate = 32, Rank = 9 });
collection5.Insert(new RankingDetail { Id = 15, RankingId = 1, PlayerId = 15, Estimate = 24, Rank = 26 });
collection5.Insert(new RankingDetail { Id = 16, RankingId = 1, PlayerId = 16, Estimate = 30, Rank = 14 });
collection5.Insert(new RankingDetail { Id = 17, RankingId = 1, PlayerId = 17, Estimate = 31, Rank = 16 });
collection5.Insert(new RankingDetail { Id = 18, RankingId = 1, PlayerId = 18, Estimate = 32, Rank = 11 });
collection5.Insert(new RankingDetail { Id = 19, RankingId = 1, PlayerId = 19, Estimate = 27, Rank = 28 });
collection5.Insert(new RankingDetail { Id = 20, RankingId = 1, PlayerId = 20, Estimate = 24, Rank = 23 });
collection5.Insert(new RankingDetail { Id = 21, RankingId = 1, PlayerId = 21, Estimate = 32, Rank = 22 });
collection5.Insert(new RankingDetail { Id = 22, RankingId = 1, PlayerId = 22, Estimate = 27, Rank = 21 });
collection5.Insert(new RankingDetail { Id = 23, RankingId = 1, PlayerId = 23, Estimate = 27, Rank = 27 });
collection5.Insert(new RankingDetail { Id = 24, RankingId = 1, PlayerId = 24, Estimate = 23, Rank = 18 });
collection5.Insert(new RankingDetail { Id = 25, RankingId = 1, PlayerId = 25, Estimate = 29, Rank = 13 });
collection5.Insert(new RankingDetail { Id = 26, RankingId = 1, PlayerId = 26, Estimate = 30, Rank = 24 });
collection5.Insert(new RankingDetail { Id = 27, RankingId = 1, PlayerId = 27, Estimate = 27, Rank = 34 });
collection5.Insert(new RankingDetail { Id = 28, RankingId = 1, PlayerId = 28, Estimate = 27, Rank = 19 });
collection5.Insert(new RankingDetail { Id = 29, RankingId = 1, PlayerId = 29, Estimate = 19, Rank = 41 });
collection5.Insert(new RankingDetail { Id = 30, RankingId = 1, PlayerId = 30, Estimate = 26, Rank = 29 });
collection5.Insert(new RankingDetail { Id = 31, RankingId = 1, PlayerId = 31, Estimate = 25, Rank = 31 });
collection5.Insert(new RankingDetail { Id = 32, RankingId = 1, PlayerId = 32, Estimate = 19, Rank = 39 });
collection5.Insert(new RankingDetail { Id = 33, RankingId = 1, PlayerId = 33, Estimate = 20, Rank = 25 });
collection5.Insert(new RankingDetail { Id = 34, RankingId = 1, PlayerId = 34, Estimate = 16, Rank = 30 });
collection5.Insert(new RankingDetail { Id = 35, RankingId = 1, PlayerId = 35, Estimate = 21, Rank = 32 });
collection5.Insert(new RankingDetail { Id = 36, RankingId = 1, PlayerId = 36, Estimate = 18, Rank = 43 });
collection5.Insert(new RankingDetail { Id = 37, RankingId = 1, PlayerId = 37, Estimate = 20, Rank = 42 });
collection5.Insert(new RankingDetail { Id = 38, RankingId = 1, PlayerId = 38, Estimate = 23, Rank = 35 });
collection5.Insert(new RankingDetail { Id = 39, RankingId = 1, PlayerId = 39, Estimate = 20, Rank = 33 });
collection5.Insert(new RankingDetail { Id = 40, RankingId = 1, PlayerId = 40, Estimate = 21, Rank = 45 });
collection5.Insert(new RankingDetail { Id = 41, RankingId = 1, PlayerId = 41, Estimate = 17, Rank = 53 });
collection5.Insert(new RankingDetail { Id = 42, RankingId = 1, PlayerId = 42, Estimate = 21, Rank = 36 });
collection5.Insert(new RankingDetail { Id = 43, RankingId = 1, PlayerId = 43, Estimate = 14, Rank = 37 });
collection5.Insert(new RankingDetail { Id = 44, RankingId = 1, PlayerId = 44, Estimate = 16, Rank = 38 });
collection5.Insert(new RankingDetail { Id = 45, RankingId = 1, PlayerId = 45, Estimate = 17, Rank = 46 });
collection5.Insert(new RankingDetail { Id = 46, RankingId = 1, PlayerId = 46, Estimate = 17, Rank = 47 });
collection5.Insert(new RankingDetail { Id = 47, RankingId = 1, PlayerId = 47, Estimate = 15, Rank = 55 });
collection5.Insert(new RankingDetail { Id = 48, RankingId = 1, PlayerId = 48, Estimate = 17, Rank = 64 });
collection5.Insert(new RankingDetail { Id = 49, RankingId = 1, PlayerId = 49, Estimate = 16, Rank = 50 });
collection5.Insert(new RankingDetail { Id = 50, RankingId = 1, PlayerId = 50, Estimate = 15, Rank = 49 });
collection5.Insert(new RankingDetail { Id = 51, RankingId = 1, PlayerId = 51, Estimate = 18, Rank = 40 });
collection5.Insert(new RankingDetail { Id = 52, RankingId = 1, PlayerId = 52, Estimate = 17, Rank = 54 });
collection5.Insert(new RankingDetail { Id = 53, RankingId = 1, PlayerId = 53, Estimate = 16, Rank = 58 });
collection5.Insert(new RankingDetail { Id = 54, RankingId = 1, PlayerId = 54, Estimate = 17, Rank = 59 });
collection5.Insert(new RankingDetail { Id = 55, RankingId = 1, PlayerId = 55, Estimate = 14, Rank = 63 });
collection5.Insert(new RankingDetail { Id = 56, RankingId = 1, PlayerId = 56, Estimate = 15, Rank = 57 });
collection5.Insert(new RankingDetail { Id = 57, RankingId = 1, PlayerId = 57, Estimate = 10, Rank = 62 });
collection5.Insert(new RankingDetail { Id = 58, RankingId = 1, PlayerId = 58, Estimate = 12, Rank = 44 });
collection5.Insert(new RankingDetail { Id = 59, RankingId = 1, PlayerId = 59, Estimate = 16, Rank = 51 });
collection5.Insert(new RankingDetail { Id = 60, RankingId = 1, PlayerId = 60, Estimate = 14, Rank = 67 });
collection5.Insert(new RankingDetail { Id = 61, RankingId = 1, PlayerId = 61, Estimate = 7, Rank = 56 });
collection5.Insert(new RankingDetail { Id = 62, RankingId = 1, PlayerId = 62, Estimate = 16, Rank = 60 });
collection5.Insert(new RankingDetail { Id = 63, RankingId = 1, PlayerId = 63, Estimate = 13, Rank = 68 });
collection5.Insert(new RankingDetail { Id = 64, RankingId = 1, PlayerId = 64, Estimate = 10, Rank = 66 });
collection5.Insert(new RankingDetail { Id = 65, RankingId = 1, PlayerId = 65, Estimate = 12, Rank = 69 });
collection5.Insert(new RankingDetail { Id = 66, RankingId = 1, PlayerId = 66, Estimate = 12, Rank = 48 });
collection5.Insert(new RankingDetail { Id = 67, RankingId = 1, PlayerId = 67, Estimate = 12, Rank = 52 });
collection5.Insert(new RankingDetail { Id = 68, RankingId = 1, PlayerId = 68, Estimate = 8, Rank = 61 });
collection5.Insert(new RankingDetail { Id = 69, RankingId = 1, PlayerId = 69, Estimate = 9, Rank = 78 });
collection5.Insert(new RankingDetail { Id = 70, RankingId = 1, PlayerId = 70, Estimate = 13, Rank = 65 });
collection5.Insert(new RankingDetail { Id = 71, RankingId = 1, PlayerId = 71, Estimate = 13, Rank = 82 });
collection5.Insert(new RankingDetail { Id = 72, RankingId = 1, PlayerId = 72, Estimate = 7, Rank = 71 });
collection5.Insert(new RankingDetail { Id = 73, RankingId = 1, PlayerId = 73, Estimate = 12, Rank = 90 });
collection5.Insert(new RankingDetail { Id = 74, RankingId = 1, PlayerId = 74, Estimate = 13, Rank = 86 });
collection5.Insert(new RankingDetail { Id = 75, RankingId = 1, PlayerId = 75, Estimate = 10, Rank = 72 });
collection5.Insert(new RankingDetail { Id = 76, RankingId = 1, PlayerId = 76, Estimate = 8, Rank = 74 });
collection5.Insert(new RankingDetail { Id = 77, RankingId = 1, PlayerId = 77, Estimate = 11, Rank = 75 });
collection5.Insert(new RankingDetail { Id = 78, RankingId = 1, PlayerId = 78, Estimate = 7, Rank = 87 });
collection5.Insert(new RankingDetail { Id = 79, RankingId = 1, PlayerId = 79, Estimate = 9, Rank = 96 });
collection5.Insert(new RankingDetail { Id = 80, RankingId = 1, PlayerId = 80, Estimate = 8, Rank = 94 });
collection5.Insert(new RankingDetail { Id = 81, RankingId = 1, PlayerId = 81, Estimate = 8, Rank = 76 });
collection5.Insert(new RankingDetail { Id = 82, RankingId = 1, PlayerId = 82, Estimate = 7, Rank = 81 });
collection5.Insert(new RankingDetail { Id = 83, RankingId = 1, PlayerId = 83, Estimate = 10, Rank = 91 });
collection5.Insert(new RankingDetail { Id = 84, RankingId = 1, PlayerId = 84, Estimate = 8, Rank = 83 });
collection5.Insert(new RankingDetail { Id = 85, RankingId = 1, PlayerId = 85, Estimate = 5, Rank = 93 });
collection5.Insert(new RankingDetail { Id = 86, RankingId = 1, PlayerId = 86, Estimate = 8, Rank = 70 });
collection5.Insert(new RankingDetail { Id = 87, RankingId = 1, PlayerId = 87, Estimate = 6, Rank = 92 });
collection5.Insert(new RankingDetail { Id = 88, RankingId = 1, PlayerId = 88, Estimate = 4, Rank = 89 });
collection5.Insert(new RankingDetail { Id = 89, RankingId = 1, PlayerId = 89, Estimate = 6, Rank = 97 });
collection5.Insert(new RankingDetail { Id = 90, RankingId = 1, PlayerId = 90, Estimate = 8, Rank = 88 });
collection5.Insert(new RankingDetail { Id = 91, RankingId = 1, PlayerId = 91, Estimate = 6, Rank = 80 });
collection5.Insert(new RankingDetail { Id = 92, RankingId = 1, PlayerId = 92, Estimate = 6, Rank = 77 });
collection5.Insert(new RankingDetail { Id = 93, RankingId = 1, PlayerId = 93, Estimate = 1, Rank = 85 });
collection5.Insert(new RankingDetail { Id = 94, RankingId = 1, PlayerId = 94, Estimate = 5, Rank = 118 });
collection5.Insert(new RankingDetail { Id = 95, RankingId = 1, PlayerId = 95, Estimate = 5, Rank = 84 });
collection5.Insert(new RankingDetail { Id = 96, RankingId = 1, PlayerId = 96, Estimate = 4, Rank = 106 });
collection5.Insert(new RankingDetail { Id = 97, RankingId = 1, PlayerId = 97, Estimate = 7, Rank = 133 });
collection5.Insert(new RankingDetail { Id = 98, RankingId = 1, PlayerId = 98, Estimate = 6, Rank = 130 });
collection5.Insert(new RankingDetail { Id = 99, RankingId = 1, PlayerId = 99, Estimate = 5, Rank = 98 });
collection5.Insert(new RankingDetail { Id = 100, RankingId = 1, PlayerId = 100, Estimate = 7, Rank = 79 });
collection5.Insert(new RankingDetail { Id = 101, RankingId = 1, PlayerId = 101, Estimate = 5, Rank = 109 });
collection5.Insert(new RankingDetail { Id = 102, RankingId = 1, PlayerId = 102, Estimate = 5, Rank = 128 });
collection5.Insert(new RankingDetail { Id = 103, RankingId = 1, PlayerId = 103, Estimate = 9, Rank = 144 });
collection5.Insert(new RankingDetail { Id = 104, RankingId = 1, PlayerId = 104, Estimate = 6, Rank = 73 });
collection5.Insert(new RankingDetail { Id = 105, RankingId = 1, PlayerId = 105, Estimate = 5, Rank = 104 });
collection5.Insert(new RankingDetail { Id = 106, RankingId = 1, PlayerId = 106, Estimate = 5, Rank = 110 });
collection5.Insert(new RankingDetail { Id = 107, RankingId = 1, PlayerId = 107, Estimate = 5, Rank = 101 });
collection5.Insert(new RankingDetail { Id = 108, RankingId = 1, PlayerId = 108, Estimate = 5, Rank = 108 });
collection5.Insert(new RankingDetail { Id = 109, RankingId = 1, PlayerId = 109, Estimate = 4, Rank = 107 });
collection5.Insert(new RankingDetail { Id = 110, RankingId = 1, PlayerId = 110, Estimate = 6, Rank = 99 });
collection5.Insert(new RankingDetail { Id = 111, RankingId = 1, PlayerId = 111, Estimate = 3, Rank = 103 });
collection5.Insert(new RankingDetail { Id = 112, RankingId = 1, PlayerId = 112, Estimate = 3, Rank = 120 });
collection5.Insert(new RankingDetail { Id = 113, RankingId = 1, PlayerId = 113, Estimate = 4, Rank = 127 });
collection5.Insert(new RankingDetail { Id = 114, RankingId = 1, PlayerId = 114, Estimate = 3, Rank = 113 });
collection5.Insert(new RankingDetail { Id = 115, RankingId = 1, PlayerId = 115, Estimate = 4, Rank = 124 });
collection5.Insert(new RankingDetail { Id = 116, RankingId = 1, PlayerId = 116, Estimate = 3, Rank = 307 });
collection5.Insert(new RankingDetail { Id = 117, RankingId = 1, PlayerId = 117, Estimate = 3, Rank = 122 });
collection5.Insert(new RankingDetail { Id = 118, RankingId = 1, PlayerId = 118, Estimate = 3, Rank = 121 });
collection5.Insert(new RankingDetail { Id = 119, RankingId = 1, PlayerId = 119, Estimate = 4, Rank = 132 });
collection5.Insert(new RankingDetail { Id = 120, RankingId = 1, PlayerId = 120, Estimate = 4, Rank = 164 });
collection5.Insert(new RankingDetail { Id = 121, RankingId = 1, PlayerId = 121, Estimate = 6, Rank = 143 });
collection5.Insert(new RankingDetail { Id = 122, RankingId = 1, PlayerId = 122, Estimate = 3, Rank = 136 });
collection5.Insert(new RankingDetail { Id = 123, RankingId = 1, PlayerId = 123, Estimate = 3, Rank = 134 });
collection5.Insert(new RankingDetail { Id = 124, RankingId = 1, PlayerId = 124, Estimate = 4, Rank = 142 });
collection5.Insert(new RankingDetail { Id = 125, RankingId = 1, PlayerId = 125, Estimate = 3, Rank = 167 });
collection5.Insert(new RankingDetail { Id = 126, RankingId = 1, PlayerId = 126, Estimate = 4, Rank = 149 });
collection5.Insert(new RankingDetail { Id = 127, RankingId = 1, PlayerId = 127, Estimate = 3, Rank = 126 });
collection5.Insert(new RankingDetail { Id = 128, RankingId = 1, PlayerId = 128, Estimate = 4, Rank = 156 });
collection5.Insert(new RankingDetail { Id = 129, RankingId = 1, PlayerId = 129, Estimate = 1, Rank = 178 });
collection5.Insert(new RankingDetail { Id = 130, RankingId = 1, PlayerId = 130, Estimate = 2, Rank = 145 });
collection5.Insert(new RankingDetail { Id = 131, RankingId = 1, PlayerId = 131, Estimate = 3, Rank = 155 });
collection5.Insert(new RankingDetail { Id = 132, RankingId = 1, PlayerId = 132, Estimate = 2, Rank = 116 });
collection5.Insert(new RankingDetail { Id = 133, RankingId = 1, PlayerId = 133, Estimate = 1 , Rank = 184 });
collection5.Insert(new RankingDetail { Id = 134, RankingId = 1, PlayerId = 134, Estimate = 3, Rank = 137 });
collection5.Insert(new RankingDetail { Id = 135, RankingId = 1, PlayerId = 135, Estimate = 2, Rank = 154 });
collection5.Insert(new RankingDetail { Id = 136, RankingId = 1, PlayerId = 136, Estimate = 3, Rank = 153 });
collection5.Insert(new RankingDetail { Id = 137, RankingId = 1, PlayerId = 137, Estimate = 3, Rank = 192 });
collection5.Insert(new RankingDetail { Id = 138, RankingId = 1, PlayerId = 138, Estimate = 3, Rank = 129 });
collection5.Insert(new RankingDetail { Id = 139, RankingId = 1, PlayerId = 139, Estimate = 5, Rank = 125 });
collection5.Insert(new RankingDetail { Id = 140, RankingId = 1, PlayerId = 140, Estimate = 2, Rank = 176 });
collection5.Insert(new RankingDetail { Id = 141, RankingId = 1, PlayerId = 141, Estimate = 2, Rank = 169 });
collection5.Insert(new RankingDetail { Id = 142, RankingId = 1, PlayerId = 142, Estimate = 2, Rank = 229 });
collection5.Insert(new RankingDetail { Id = 143, RankingId = 1, PlayerId = 143, Estimate = 2, Rank = 171 });
collection5.Insert(new RankingDetail { Id = 144, RankingId = 1, PlayerId = 144, Estimate = 3, Rank = 138 });
collection5.Insert(new RankingDetail { Id = 145, RankingId = 1, PlayerId = 145, Estimate = 4, Rank = 247 });
collection5.Insert(new RankingDetail { Id = 146, RankingId = 1, PlayerId = 146, Estimate = 2, Rank = 148 });
collection5.Insert(new RankingDetail { Id = 147, RankingId = 1, PlayerId = 147, Estimate = 1, Rank = 141 });
collection5.Insert(new RankingDetail { Id = 148, RankingId = 1, PlayerId = 148, Estimate = 4, Rank = 166 });
collection5.Insert(new RankingDetail { Id = 149, RankingId = 1, PlayerId = 149, Estimate = 2, Rank = 146 });
collection5.Insert(new RankingDetail { Id = 150, RankingId = 1, PlayerId = 150, Estimate = 2, Rank = 198 });
collection5.Insert(new RankingDetail { Id = 151, RankingId = 1, PlayerId = 151, Estimate = 2, Rank = 95 });
collection5.Insert(new RankingDetail { Id = 152, RankingId = 1, PlayerId = 152, Estimate = 2, Rank = 196 });
collection5.Insert(new RankingDetail { Id = 153, RankingId = 1, PlayerId = 153, Estimate = 2, Rank = 100 });
collection5.Insert(new RankingDetail { Id = 154, RankingId = 1, PlayerId = 154, Estimate = 4, Rank = 177 });
collection5.Insert(new RankingDetail { Id = 155, RankingId = 1, PlayerId = 155, Estimate = 2, Rank = 117 });
collection5.Insert(new RankingDetail { Id = 156, RankingId = 1, PlayerId = 156, Estimate = 2, Rank = 115 });
collection5.Insert(new RankingDetail { Id = 157, RankingId = 1, PlayerId = 157, Estimate = 3, Rank = 157 });
collection5.Insert(new RankingDetail { Id = 158, RankingId = 1, PlayerId = 158, Estimate = 2, Rank = 102 });
collection5.Insert(new RankingDetail { Id = 159, RankingId = 1, PlayerId = 159, Estimate = 2, Rank = 188 });
collection5.Insert(new RankingDetail { Id = 160, RankingId = 1, PlayerId = 160, Estimate = 2, Rank = 112 });
collection5.Insert(new RankingDetail { Id = 161, RankingId = 1, PlayerId = 161, Estimate = 1, Rank = 135 });
collection5.Insert(new RankingDetail { Id = 162, RankingId = 1, PlayerId = 162, Estimate = 2, Rank = 159 });
collection5.Insert(new RankingDetail { Id = 163, RankingId = 1, PlayerId = 163, Estimate = 2, Rank = 114 });
collection5.Insert(new RankingDetail { Id = 164, RankingId = 1, PlayerId = 164, Estimate = 1, Rank = 105 });
collection5.Insert(new RankingDetail { Id = 165, RankingId = 1, PlayerId = 165, Estimate = 2, Rank = 175 });
collection5.Insert(new RankingDetail { Id = 166, RankingId = 1, PlayerId = 166, Estimate = 2, Rank = 186 });
collection5.Insert(new RankingDetail { Id = 167, RankingId = 1, PlayerId = 167, Estimate = 2, Rank = 111 });
collection5.Insert(new RankingDetail { Id = 168, RankingId = 1, PlayerId = 168, Estimate = 1, Rank = 235 });
collection5.Insert(new RankingDetail { Id = 169, RankingId = 1, PlayerId = 169, Estimate = 2, Rank = 205 });
collection5.Insert(new RankingDetail { Id = 170, RankingId = 1, PlayerId = 170, Estimate = 3, Rank = 160 });
collection5.Insert(new RankingDetail { Id = 171, RankingId = 1, PlayerId = 171, Estimate = 2, Rank = 206 });
collection5.Insert(new RankingDetail { Id = 172, RankingId = 1, PlayerId = 172, Estimate = 2, Rank = 238 });
collection5.Insert(new RankingDetail { Id = 173, RankingId = 1, PlayerId = 173, Estimate = 1, Rank = 163 });
collection5.Insert(new RankingDetail { Id = 174, RankingId = 1, PlayerId = 174, Estimate = 3, Rank = 162 });
collection5.Insert(new RankingDetail { Id = 175, RankingId = 1, PlayerId = 175, Estimate = 3, Rank = 150 });
collection5.Insert(new RankingDetail { Id = 176, RankingId = 1, PlayerId = 176, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 177, RankingId = 1, PlayerId = 177, Estimate = 1, Rank = 140 });
collection5.Insert(new RankingDetail { Id = 178, RankingId = 1, PlayerId = 178, Estimate = 2, Rank = 228 });
collection5.Insert(new RankingDetail { Id = 179, RankingId = 1, PlayerId = 179, Estimate = 2, Rank = 232 });
collection5.Insert(new RankingDetail { Id = 180, RankingId = 1, PlayerId = 180, Estimate = 1, Rank = 210 });
collection5.Insert(new RankingDetail { Id = 181, RankingId = 1, PlayerId = 181, Estimate = 3, Rank = 165 });
collection5.Insert(new RankingDetail { Id = 182, RankingId = 1, PlayerId = 182, Estimate = 1, Rank = 189 });
collection5.Insert(new RankingDetail { Id = 183, RankingId = 1, PlayerId = 183, Estimate = 1, Rank = 139 });
collection5.Insert(new RankingDetail { Id = 184, RankingId = 1, PlayerId = 184, Estimate = 2, Rank = 298 });
collection5.Insert(new RankingDetail { Id = 185, RankingId = 1, PlayerId = 185, Estimate = 2, Rank = 220 });
collection5.Insert(new RankingDetail { Id = 186, RankingId = 1, PlayerId = 186, Estimate = 2, Rank = 194 });
collection5.Insert(new RankingDetail { Id = 187, RankingId = 1, PlayerId = 187, Estimate = 1, Rank = 119 });
collection5.Insert(new RankingDetail { Id = 188, RankingId = 1, PlayerId = 188, Estimate = 1, Rank = 147 });
collection5.Insert(new RankingDetail { Id = 189, RankingId = 1, PlayerId = 189, Estimate = 2, Rank = 213 });
collection5.Insert(new RankingDetail { Id = 190, RankingId = 1, PlayerId = 190, Estimate = 2, Rank = 168 });
collection5.Insert(new RankingDetail { Id = 191, RankingId = 1, PlayerId = 191, Estimate = 1, Rank = 123 });
collection5.Insert(new RankingDetail { Id = 192, RankingId = 1, PlayerId = 192, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 193, RankingId = 1, PlayerId = 193, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 194, RankingId = 1, PlayerId = 194, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 195, RankingId = 1, PlayerId = 195, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 196, RankingId = 1, PlayerId = 196, Estimate = 2, Rank = 264 });
collection5.Insert(new RankingDetail { Id = 197, RankingId = 1, PlayerId = 197, Estimate = 1, Rank = 261 });
collection5.Insert(new RankingDetail { Id = 198, RankingId = 1, PlayerId = 198, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 199, RankingId = 1, PlayerId = 199, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 200, RankingId = 1, PlayerId = 200, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 201, RankingId = 1, PlayerId = 201, Estimate = 2, Rank = 190 });
collection5.Insert(new RankingDetail { Id = 202, RankingId = 1, PlayerId = 202, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 203, RankingId = 1, PlayerId = 203, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 204, RankingId = 1, PlayerId = 204, Estimate = 1, Rank = 274 });
collection5.Insert(new RankingDetail { Id = 205, RankingId = 1, PlayerId = 205, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 206, RankingId = 1, PlayerId = 206, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 207, RankingId = 1, PlayerId = 207, Estimate = 1, Rank = 250 });
collection5.Insert(new RankingDetail { Id = 208, RankingId = 1, PlayerId = 208, Estimate = 1, Rank = 299 });
collection5.Insert(new RankingDetail { Id = 209, RankingId = 1, PlayerId = 209, Estimate = 1, Rank = 271 });
collection5.Insert(new RankingDetail { Id = 210, RankingId = 1, PlayerId = 210, Estimate = 1, Rank = 240 });
collection5.Insert(new RankingDetail { Id = 211, RankingId = 1, PlayerId = 211, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 212, RankingId = 1, PlayerId = 212, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 213, RankingId = 1, PlayerId = 213, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 214, RankingId = 1, PlayerId = 214, Estimate = 1, Rank = 272 });
collection5.Insert(new RankingDetail { Id = 215, RankingId = 1, PlayerId = 215, Estimate = 1, Rank = 257 });
collection5.Insert(new RankingDetail { Id = 216, RankingId = 1, PlayerId = 216, Estimate = 1, Rank = 225 });
collection5.Insert(new RankingDetail { Id = 217, RankingId = 1, PlayerId = 217, Estimate = 1, Rank = 243 });
collection5.Insert(new RankingDetail { Id = 218, RankingId = 1, PlayerId = 218, Estimate = 1, Rank = 151 });
collection5.Insert(new RankingDetail { Id = 219, RankingId = 1, PlayerId = 219, Estimate = 1, Rank = 179 });
collection5.Insert(new RankingDetail { Id = 220, RankingId = 1, PlayerId = 220, Estimate = 1, Rank = 158 });
collection5.Insert(new RankingDetail { Id = 221, RankingId = 1, PlayerId = 221, Estimate = 1, Rank = 259 });
collection5.Insert(new RankingDetail { Id = 222, RankingId = 1, PlayerId = 222, Estimate = 1, Rank = 303 });
collection5.Insert(new RankingDetail { Id = 223, RankingId = 1, PlayerId = 223, Estimate = 1, Rank = 266 });
collection5.Insert(new RankingDetail { Id = 224, RankingId = 1, PlayerId = 224, Estimate = 1, Rank = 242 });
collection5.Insert(new RankingDetail { Id = 225, RankingId = 1, PlayerId = 225, Estimate = 1, Rank = 181 });
collection5.Insert(new RankingDetail { Id = 226, RankingId = 1, PlayerId = 226, Estimate = 1, Rank = 182 });
collection5.Insert(new RankingDetail { Id = 227, RankingId = 1, PlayerId = 227, Estimate = 1, Rank = 174 });
collection5.Insert(new RankingDetail { Id = 228, RankingId = 1, PlayerId = 228, Estimate = 1, Rank = 173 });
collection5.Insert(new RankingDetail { Id = 229, RankingId = 1, PlayerId = 229, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 230, RankingId = 1, PlayerId = 230, Estimate = 1, Rank = 185 });
collection5.Insert(new RankingDetail { Id = 231, RankingId = 1, PlayerId = 231, Estimate = 1, Rank = 200 });
collection5.Insert(new RankingDetail { Id = 232, RankingId = 1, PlayerId = 232, Estimate = 2, Rank = 302 });
collection5.Insert(new RankingDetail { Id = 233, RankingId = 1, PlayerId = 233, Estimate = 1, Rank = 276 });
collection5.Insert(new RankingDetail { Id = 234, RankingId = 1, PlayerId = 234, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 235, RankingId = 1, PlayerId = 235, Estimate = 1, Rank = 267 });
collection5.Insert(new RankingDetail { Id = 236, RankingId = 1, PlayerId = 236, Estimate = 1, Rank = 294 });
collection5.Insert(new RankingDetail { Id = 237, RankingId = 1, PlayerId = 237, Estimate = 1, Rank = 269 });
collection5.Insert(new RankingDetail { Id = 238, RankingId = 1, PlayerId = 238, Estimate = 1, Rank = 289 });
collection5.Insert(new RankingDetail { Id = 239, RankingId = 1, PlayerId = 239, Estimate = 1, Rank = 183 });
collection5.Insert(new RankingDetail { Id = 240, RankingId = 1, PlayerId = 240, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 241, RankingId = 1, PlayerId = 241, Estimate = 1, Rank = 251 });
collection5.Insert(new RankingDetail { Id = 242, RankingId = 1, PlayerId = 242, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 243, RankingId = 1, PlayerId = 243, Estimate = 1, Rank = 292 });
collection5.Insert(new RankingDetail { Id = 244, RankingId = 1, PlayerId = 244, Estimate = 1, Rank = 212 });
collection5.Insert(new RankingDetail { Id = 245, RankingId = 1, PlayerId = 245, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 246, RankingId = 1, PlayerId = 246, Estimate = 1, Rank = 295 });
collection5.Insert(new RankingDetail { Id = 247, RankingId = 1, PlayerId = 247, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 248, RankingId = 1, PlayerId = 248, Estimate = 1, Rank = 233 });
collection5.Insert(new RankingDetail { Id = 249, RankingId = 1, PlayerId = 249, Estimate = 1, Rank = 209 });
collection5.Insert(new RankingDetail { Id = 250, RankingId = 1, PlayerId = 250, Estimate = 1, Rank = 187 });
collection5.Insert(new RankingDetail { Id = 251, RankingId = 1, PlayerId = 251, Estimate = 1, Rank = 197 });
collection5.Insert(new RankingDetail { Id = 252, RankingId = 1, PlayerId = 252, Estimate = 1, Rank = 170 });
collection5.Insert(new RankingDetail { Id = 253, RankingId = 1, PlayerId = 253, Estimate = 1, Rank = 284 });
collection5.Insert(new RankingDetail { Id = 254, RankingId = 1, PlayerId = 254, Estimate = 1, Rank = 172 });
collection5.Insert(new RankingDetail { Id = 255, RankingId = 1, PlayerId = 255, Estimate = 1, Rank = 300 });
collection5.Insert(new RankingDetail { Id = 256, RankingId = 1, PlayerId = 256, Estimate = 1, Rank = 199 });
collection5.Insert(new RankingDetail { Id = 257, RankingId = 1, PlayerId = 257, Estimate = 1, Rank = 191 });
collection5.Insert(new RankingDetail { Id = 258, RankingId = 1, PlayerId = 258, Estimate = 1, Rank = 282 });
collection5.Insert(new RankingDetail { Id = 259, RankingId = 1, PlayerId = 259, Estimate = 1, Rank = 216 });
collection5.Insert(new RankingDetail { Id = 260, RankingId = 1, PlayerId = 260, Estimate = 1, Rank = 262 });
collection5.Insert(new RankingDetail { Id = 261, RankingId = 1, PlayerId = 261, Estimate = 1, Rank = 306 });
collection5.Insert(new RankingDetail { Id = 262, RankingId = 1, PlayerId = 262, Estimate = 1, Rank = 152 });
collection5.Insert(new RankingDetail { Id = 263, RankingId = 1, PlayerId = 263, Estimate = 1, Rank = 265 });
collection5.Insert(new RankingDetail { Id = 264, RankingId = 1, PlayerId = 264, Estimate = 1, Rank = 161 });
collection5.Insert(new RankingDetail { Id = 265, RankingId = 1, PlayerId = 265, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 266, RankingId = 1, PlayerId = 266, Estimate = 1, Rank = 277 });
collection5.Insert(new RankingDetail { Id = 267, RankingId = 1, PlayerId = 267, Estimate = 1, Rank = 254 });
collection5.Insert(new RankingDetail { Id = 268, RankingId = 1, PlayerId = 268, Estimate = 1, Rank = 286 });
collection5.Insert(new RankingDetail { Id = 269, RankingId = 1, PlayerId = 269, Estimate = 1, Rank = 308 });
collection5.Insert(new RankingDetail { Id = 270, RankingId = 1, PlayerId = 270, Estimate = 1, Rank = 131 });
collection5.Insert(new RankingDetail { Id = 271, RankingId = 1, PlayerId = 271, Estimate = 1, Rank = 283 });
collection5.Insert(new RankingDetail { Id = 272, RankingId = 1, PlayerId = 272, Estimate = 1, Rank = 279 });
collection5.Insert(new RankingDetail { Id = 273, RankingId = 1, PlayerId = 273, Estimate = 1, Rank = 208 });
collection5.Insert(new RankingDetail { Id = 274, RankingId = 1, PlayerId = 274, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 275, RankingId = 1, PlayerId = 275, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 276, RankingId = 1, PlayerId = 276, Estimate = 1, Rank = 297 });
collection5.Insert(new RankingDetail { Id = 277, RankingId = 1, PlayerId = 277, Estimate = 1, Rank = 246 });
collection5.Insert(new RankingDetail { Id = 278, RankingId = 1, PlayerId = 278, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 279, RankingId = 1, PlayerId = 279, Estimate = 1, Rank = 211 });
collection5.Insert(new RankingDetail { Id = 280, RankingId = 1, PlayerId = 280, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 281, RankingId = 1, PlayerId = 281, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 282, RankingId = 1, PlayerId = 282, Estimate = 1, Rank = 275 });
collection5.Insert(new RankingDetail { Id = 283, RankingId = 1, PlayerId = 283, Estimate = 1, Rank = 301 });
collection5.Insert(new RankingDetail { Id = 284, RankingId = 1, PlayerId = 284, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 285, RankingId = 1, PlayerId = 285, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 286, RankingId = 1, PlayerId = 286, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 287, RankingId = 1, PlayerId = 287, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 288, RankingId = 1, PlayerId = 288, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 289, RankingId = 1, PlayerId = 289, Estimate = 1, Rank = 290 });
collection5.Insert(new RankingDetail { Id = 290, RankingId = 1, PlayerId = 290, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 291, RankingId = 1, PlayerId = 291, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 292, RankingId = 1, PlayerId = 292, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 293, RankingId = 1, PlayerId = 293, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 294, RankingId = 1, PlayerId = 294, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 295, RankingId = 1, PlayerId = 295, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 296, RankingId = 1, PlayerId = 296, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 297, RankingId = 1, PlayerId = 297, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 298, RankingId = 1, PlayerId = 298, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 299, RankingId = 1, PlayerId = 299, Estimate = 1, Rank = 287 });
collection5.Insert(new RankingDetail { Id = 300, RankingId = 1, PlayerId = 300, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 301, RankingId = 1, PlayerId = 301, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 302, RankingId = 1, PlayerId = 302, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 303, RankingId = 1, PlayerId = 303, Estimate = 1, Rank = 304 });
collection5.Insert(new RankingDetail { Id = 304, RankingId = 1, PlayerId = 304, Estimate = 1, Rank = 222 });
collection5.Insert(new RankingDetail { Id = 305, RankingId = 1, PlayerId = 305, Estimate = 1, Rank = 258 });
collection5.Insert(new RankingDetail { Id = 306, RankingId = 1, PlayerId = 306, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 307, RankingId = 1, PlayerId = 307, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 308, RankingId = 1, PlayerId = 308, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 309, RankingId = 1, PlayerId = 309, Estimate = 1, Rank = 273 });
collection5.Insert(new RankingDetail { Id = 310, RankingId = 1, PlayerId = 310, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 311, RankingId = 1, PlayerId = 311, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 312, RankingId = 1, PlayerId = 312, Estimate = 1, Rank = 260 });
collection5.Insert(new RankingDetail { Id = 313, RankingId = 1, PlayerId = 313, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 314, RankingId = 1, PlayerId = 314, Estimate = 1, Rank = 280 });
collection5.Insert(new RankingDetail { Id = 315, RankingId = 1, PlayerId = 315, Estimate = 1, Rank = 263 });
collection5.Insert(new RankingDetail { Id = 316, RankingId = 1, PlayerId = 316, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 317, RankingId = 1, PlayerId = 317, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 318, RankingId = 1, PlayerId = 318, Estimate = 1, Rank = 227 });
collection5.Insert(new RankingDetail { Id = 319, RankingId = 1, PlayerId = 319, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 320, RankingId = 1, PlayerId = 320, Estimate = 1, Rank = 255 });
collection5.Insert(new RankingDetail { Id = 321, RankingId = 1, PlayerId = 321, Estimate = 1, Rank = 224 });
collection5.Insert(new RankingDetail { Id = 322, RankingId = 1, PlayerId = 322, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 323, RankingId = 1, PlayerId = 323, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 324, RankingId = 1, PlayerId = 324, Estimate = 1, Rank = 219 });
collection5.Insert(new RankingDetail { Id = 325, RankingId = 1, PlayerId = 325, Estimate = 1, Rank = 1000 });
collection5.Insert(new RankingDetail { Id = 326, RankingId = 1, PlayerId = 326, Estimate = 1, Rank = 285 });
collection5.Insert(new RankingDetail { Id = 327, RankingId = 1, PlayerId = 327, Estimate = 1, Rank = 1000 });


            var collection6 = database.GetCollection<BidDetail>(typeof(BidDetail).Name);
            collection6.RemoveAll();
            //collection6.Insert(new BidDetail { Id = 0, AuctionId = 1, PlayerId = 2, OwnerId = 5, BidAmount = 10 });
            //collection6.Insert(new BidDetail { Id = 1, AuctionId = 1, PlayerId = 5, OwnerId = 4, BidAmount = 5 });

        }
    }
}
