using System;
using System.Linq;
using MongoDB.Driver;
using Resources;

namespace DataLoader
{
    class Program
    {
        // ReSharper disable UnusedParameter.Local
        static void Main(string[] args)
        // ReSharper restore UnusedParameter.Local
        {
            //var server = MongoServer.Create("mongodb://steve.hebert:grandam@staff.mongohq.com:10040/openlocker_db");
            var server = MongoServer.Create("mongodb://localhost:27017/");
            server.CreateDatabaseSettings("openlocker_db");

            var database = server.GetDatabase("openlocker_db");

            var collection = database.GetCollection<Player>(typeof(Player).Name);

            foreach (var player in collection.FindAll().AsEnumerable())
                Console.Write(player);

            collection.RemoveAll();

            collection.Insert(new Player { Id = 1, Name = "Vick, Michael", Position = "QB", Team = "PHI" });
            collection.Insert(new Player { Id = 2, Name = "Foster, Arian", Position = "RB", Team = "HOU" });
            collection.Insert(new Player { Id = 3, Name = "White, Roddy", Position = "WR", Team = "ATL" });
            collection.Insert(new Player { Id = 4, Name = "Gates, Antonio", Position = "TE", Team = "SD" });
            collection.Insert(new Player { Id = 5, Name = "Rodgers, Aaron", Position = "QB", Team = "GB" });
            collection.Insert(new Player { Id = 6, Name = "Rice, Ray", Position = "RB", Team = "BAL" });
            collection.Insert(new Player { Id = 7, Name = "Johnson, Calvin", Position = "WR", Team = "DET" });
            collection.Insert(new Player { Id = 8, Name = "Finley, Jermichael", Position = "TE", Team = "GB" });
            collection.Insert(new Player { Id = 9, Name = "Brady, Tom", Position = "QB", Team = "NE" });
            collection.Insert(new Player { Id = 10, Name = "Charles, Jamaal", Position = "RB", Team = "KC" });
            collection.Insert(new Player { Id = 11, Name = "Johnson, Andre", Position = "WR", Team = "HOU" });
            collection.Insert(new Player { Id = 12, Name = "Clark, Dallas", Position = "TE", Team = "IND" });
            collection.Insert(new Player { Id = 13, Name = "Brees, Drew", Position = "QB", Team = "NO" });
            collection.Insert(new Player { Id = 14, Name = "Peterson, Adrian", Position = "RB", Team = "MIN" });
            collection.Insert(new Player { Id = 15, Name = "Fitzgerald, Larry", Position = "WR", Team = "ARI" });
            collection.Insert(new Player { Id = 16, Name = "Witten, Jason", Position = "TE", Team = "DAL" });
            collection.Insert(new Player { Id = 17, Name = "Rivers, Philip", Position = "QB", Team = "SD" });
            collection.Insert(new Player { Id = 18, Name = "Johnson, Chris", Position = "RB", Team = "TEN" });
            collection.Insert(new Player { Id = 19, Name = "Jackson, Vincent", Position = "WR", Team = "SD" });
            collection.Insert(new Player { Id = 20, Name = "Davis, Vernon", Position = "TE", Team = "SF" });
            collection.Insert(new Player { Id = 21, Name = "Manning, Peyton", Position = "QB", Team = "IND" });
            collection.Insert(new Player { Id = 22, Name = "McCoy, LeSean", Position = "RB", Team = "PHI" });
            collection.Insert(new Player { Id = 23, Name = "Bowe, Dwayne", Position = "WR", Team = "KC" });
            collection.Insert(new Player { Id = 24, Name = "Daniels, Owen", Position = "TE", Team = "HOU" });
            collection.Insert(new Player { Id = 25, Name = "Ryan, Matt", Position = "QB", Team = "ATL" });
            collection.Insert(new Player { Id = 26, Name = "Jones Drew, Maurice", Position = "RB", Team = "JAC" });
            collection.Insert(new Player { Id = 27, Name = "Jennings, Greg", Position = "WR", Team = "GB" });
            collection.Insert(new Player { Id = 28, Name = "Graham, Jimmy", Position = "TE", Team = "NO" });
            collection.Insert(new Player { Id = 29, Name = "Romo, Tony", Position = "QB", Team = "DAL" });
            collection.Insert(new Player { Id = 30, Name = "Turner, Michael", Position = "RB", Team = "ATL" });
            collection.Insert(new Player { Id = 31, Name = "Nicks, Hakeem", Position = "WR", Team = "NYG" });
            collection.Insert(new Player { Id = 32, Name = "Lewis, Marcedes", Position = "TE", Team = "JAC" });
            collection.Insert(new Player { Id = 33, Name = "Schaub, Matt", Position = "QB", Team = "HOU" });
            collection.Insert(new Player { Id = 34, Name = "Mendenhall, Rashard", Position = "RB", Team = "PIT" });
            collection.Insert(new Player { Id = 35, Name = "Austin, Miles", Position = "WR", Team = "DAL" });
            collection.Insert(new Player { Id = 36, Name = "Miller, Zach", Position = "TE", Team = "SEA" });
            collection.Insert(new Player { Id = 37, Name = "Manning, Eli", Position = "QB", Team = "NYG" });
            collection.Insert(new Player { Id = 38, Name = "Blount, LeGarrette", Position = "RB", Team = "TB" });
            collection.Insert(new Player { Id = 39, Name = "Wallace, Mike", Position = "WR", Team = "PIT" });
            collection.Insert(new Player { Id = 40, Name = "Pettigrew, Brandon", Position = "TE", Team = "DET" });
            collection.Insert(new Player { Id = 41, Name = "Roethlisberger, Ben", Position = "QB", Team = "PIT" });
            collection.Insert(new Player { Id = 42, Name = "Greene, Shonn", Position = "RB", Team = "NYJ" });
            collection.Insert(new Player { Id = 43, Name = "Williams, Mike", Position = "WR", Team = "TB" });
            collection.Insert(new Player { Id = 44, Name = "Winslow, Kellen", Position = "TE", Team = "TB" });
            collection.Insert(new Player { Id = 45, Name = "Cassel, Matt", Position = "QB", Team = "KC" });
            collection.Insert(new Player { Id = 46, Name = "Hillis, Peyton", Position = "RB", Team = "CLE" });
            collection.Insert(new Player { Id = 47, Name = "Wayne, Reggie", Position = "WR", Team = "IND" });
            collection.Insert(new Player { Id = 48, Name = "Gonzalez, Tony", Position = "TE", Team = "ATL" });
            collection.Insert(new Player { Id = 49, Name = "Bradford, Sam", Position = "QB", Team = "STL" });
            collection.Insert(new Player { Id = 50, Name = "Bradshaw, Ahmad", Position = "RB", Team = "NYG" });
            collection.Insert(new Player { Id = 51, Name = "Jackson, DeSean", Position = "WR", Team = "PHI" });
            collection.Insert(new Player { Id = 52, Name = "Celek, Brent", Position = "TE", Team = "PHI" });
            collection.Insert(new Player { Id = 53, Name = "Stafford, Matthew", Position = "QB", Team = "DET" });
            collection.Insert(new Player { Id = 54, Name = "McFadden, Darren", Position = "RB", Team = "OAK" });
            collection.Insert(new Player { Id = 55, Name = "Manningham, Mario", Position = "WR", Team = "NYG" });
            collection.Insert(new Player { Id = 56, Name = "Gronkowski, Rob", Position = "TE", Team = "NE" });
            collection.Insert(new Player { Id = 57, Name = "Freeman, Josh", Position = "QB", Team = "TB" });
            collection.Insert(new Player { Id = 58, Name = "Gore, Frank", Position = "RB", Team = "SF" });
            collection.Insert(new Player { Id = 59, Name = "Britt, Kenny", Position = "WR", Team = "TEN" });
            collection.Insert(new Player { Id = 60, Name = "Shiancoe, Visanthe", Position = "TE", Team = "MIN" });
            collection.Insert(new Player { Id = 61, Name = "Flacco, Joe", Position = "QB", Team = "BAL" });
            collection.Insert(new Player { Id = 62, Name = "Forte, Matt", Position = "RB", Team = "CHI" });
            collection.Insert(new Player { Id = 63, Name = "Bryant, Dez", Position = "WR", Team = "DAL" });
            collection.Insert(new Player { Id = 64, Name = "Keller, Dustin", Position = "TE", Team = "NYJ" });
            collection.Insert(new Player { Id = 65, Name = "Kolb, Kevin", Position = "QB", Team = "ARI" });
            collection.Insert(new Player { Id = 66, Name = "Ingram, Mark", Position = "RB", Team = "NO" });
            collection.Insert(new Player { Id = 67, Name = "Marshall, Brandon", Position = "WR", Team = "MIA" });
            collection.Insert(new Player { Id = 68, Name = "Cooley, Chris", Position = "TE", Team = "WAS" });
            collection.Insert(new Player { Id = 69, Name = "Fitzpatrick, Ryan", Position = "QB", Team = "BUF" });
            collection.Insert(new Player { Id = 70, Name = "Jackson, Steven", Position = "RB", Team = "STL" });
            collection.Insert(new Player { Id = 71, Name = "Ochocinco, Chad", Position = "WR", Team = "NE" });
            collection.Insert(new Player { Id = 72, Name = "Thomas, Julius", Position = "TE", Team = "DEN" });
            collection.Insert(new Player { Id = 73, Name = "Orton, Kyle", Position = "QB", Team = "DEN" });
            collection.Insert(new Player { Id = 74, Name = "Jones, Felix", Position = "RB", Team = "DAL" });
            collection.Insert(new Player { Id = 75, Name = "Holmes, Santonio", Position = "WR", Team = "NYJ" });
            collection.Insert(new Player { Id = 76, Name = "Dickson, Ed", Position = "TE", Team = "BAL" });
            collection.Insert(new Player { Id = 77, Name = "Sanchez, Mark", Position = "QB", Team = "NYJ" });
            collection.Insert(new Player { Id = 78, Name = "Best, Jahvid", Position = "RB", Team = "DET" });
            collection.Insert(new Player { Id = 79, Name = "Colston, Marques", Position = "WR", Team = "NO" });
            collection.Insert(new Player { Id = 80, Name = "Gresham, Jermaine", Position = "TE", Team = "CIN" });
            collection.Insert(new Player { Id = 81, Name = "Hasselbeck, Matt", Position = "QB", Team = "TEN" });
            collection.Insert(new Player { Id = 82, Name = "Lynch, Marshawn", Position = "RB", Team = "SEA" });
            collection.Insert(new Player { Id = 83, Name = "Boldin, Anquan", Position = "WR", Team = "BAL" });
            collection.Insert(new Player { Id = 84, Name = "Moeaki, Tony", Position = "TE", Team = "KC" });
            collection.Insert(new Player { Id = 85, Name = "Henne, Chad", Position = "QB", Team = "MIA" });
            collection.Insert(new Player { Id = 86, Name = "Jackson, Fred", Position = "RB", Team = "BUF" });
            collection.Insert(new Player { Id = 87, Name = "Johnson, Steve", Position = "WR", Team = "BUF" });
            collection.Insert(new Player { Id = 88, Name = "Miller, Heath", Position = "TE", Team = "PIT" });
            collection.Insert(new Player { Id = 89, Name = "Cutler, Jay", Position = "QB", Team = "CHI" });
            collection.Insert(new Player { Id = 90, Name = "Grant, Ryan", Position = "RB", Team = "GB" });
            collection.Insert(new Player { Id = 91, Name = "Lloyd, Brandon", Position = "WR", Team = "DEN" });
            collection.Insert(new Player { Id = 92, Name = "Hernandez, Aaron", Position = "TE", Team = "NE" });
            collection.Insert(new Player { Id = 93, Name = "McNabb, Donovan", Position = "QB", Team = "MIN" });
            collection.Insert(new Player { Id = 94, Name = "Wells, Chris", Position = "RB", Team = "ARI" });
            collection.Insert(new Player { Id = 95, Name = "Moore, Lance", Position = "WR", Team = "NO" });
            collection.Insert(new Player { Id = 96, Name = "Watson, Ben", Position = "TE", Team = "CLE" });
            collection.Insert(new Player { Id = 97, Name = "McCoy, Colt", Position = "QB", Team = "CLE" });
            collection.Insert(new Player { Id = 98, Name = "Williams, DeAngelo", Position = "RB", Team = "CAR" });
            collection.Insert(new Player { Id = 99, Name = "Harvin, Percy", Position = "WR", Team = "MIN" });
            collection.Insert(new Player { Id = 100, Name = "Olsen, Greg", Position = "TE", Team = "CAR" });
            collection.Insert(new Player { Id = 101, Name = "Campbell, Jason", Position = "QB", Team = "OAK" });
            collection.Insert(new Player { Id = 102, Name = "Mathews, Ryan", Position = "RB", Team = "SD" });
            collection.Insert(new Player { Id = 103, Name = "Maclin, Jeremy", Position = "WR", Team = "PHI" });
            collection.Insert(new Player { Id = 104, Name = "Davis, Fred", Position = "TE", Team = "WAS" });
            collection.Insert(new Player { Id = 105, Name = "Newton, Cam", Position = "QB", Team = "CAR" });
            collection.Insert(new Player { Id = 106, Name = "Moreno, Knowshon", Position = "RB", Team = "DEN" });
            collection.Insert(new Player { Id = 107, Name = "Jones, Julio", Position = "WR", Team = "ATL" });
            collection.Insert(new Player { Id = 108, Name = "Heap, Todd", Position = "TE", Team = "ARI" });
            collection.Insert(new Player { Id = 109, Name = "Dalton, Andy", Position = "QB", Team = "CIN" });
            collection.Insert(new Player { Id = 110, Name = "Benson, Cedric", Position = "RB", Team = "CIN" });
            collection.Insert(new Player { Id = 111, Name = "Burress, Plaxico", Position = "WR", Team = "NYJ" });
            collection.Insert(new Player { Id = 112, Name = "Boss, Kevin", Position = "TE", Team = "OAK" });
            collection.Insert(new Player { Id = 113, Name = "Gabbert, Blaine", Position = "QB", Team = "JAC" });
            collection.Insert(new Player { Id = 114, Name = "Torain, Ryan", Position = "RB", Team = "WAS" });
            collection.Insert(new Player { Id = 115, Name = "Welker, Wes", Position = "WR", Team = "NE" });
            collection.Insert(new Player { Id = 116, Name = "Fasano, Anthony", Position = "TE", Team = "MIA" });
            collection.Insert(new Player { Id = 117, Name = "Smith, Alex", Position = "QB", Team = "SF" });
            collection.Insert(new Player { Id = 118, Name = "Stewart, Jonathan", Position = "RB", Team = "CAR" });
            collection.Insert(new Player { Id = 119, Name = "Smith, Steve", Position = "WR", Team = "CAR" });
            collection.Insert(new Player { Id = 120, Name = "Shockey, Jeremy", Position = "TE", Team = "CAR" });
            collection.Insert(new Player { Id = 121, Name = "Gradkowski, Bruce", Position = "QB", Team = "CIN" });
            collection.Insert(new Player { Id = 122, Name = "Green-Ellis, BenJarvus", Position = "RB", Team = "NE" });
            collection.Insert(new Player { Id = 123, Name = "Moss, Santana", Position = "WR", Team = "WAS" });
            collection.Insert(new Player { Id = 124, Name = "Davis, Kellen", Position = "TE", Team = "CHI" });
            collection.Insert(new Player { Id = 125, Name = "Garrard, David", Position = "QB", Team = "JAC" });
            collection.Insert(new Player { Id = 126, Name = "Tolbert, Mike", Position = "RB", Team = "SD" });
            collection.Insert(new Player { Id = 127, Name = "Collie, Austin", Position = "WR", Team = "IND" });
            collection.Insert(new Player { Id = 128, Name = "Fells, Daniel", Position = "TE", Team = "DEN" });
            collection.Insert(new Player { Id = 129, Name = "Beck, John", Position = "QB", Team = "WAS" });
            collection.Insert(new Player { Id = 130, Name = "McGahee, Willis", Position = "RB", Team = "DEN" });
            collection.Insert(new Player { Id = 131, Name = "Rice, Sidney", Position = "WR", Team = "SEA" });
            collection.Insert(new Player { Id = 132, Name = "Cook, Jared", Position = "TE", Team = "TEN" });
            collection.Insert(new Player { Id = 133, Name = "Hoyer, Brian", Position = "QB", Team = "NE" });
            collection.Insert(new Player { Id = 134, Name = "Bush, Reggie", Position = "RB", Team = "MIA" });
            collection.Insert(new Player { Id = 135, Name = "Williams, Roy", Position = "WR", Team = "CHI" });
            collection.Insert(new Player { Id = 136, Name = "Pitta, Dennis", Position = "TE", Team = "BAL" });
            collection.Insert(new Player { Id = 137, Name = "Jackson, Tarvaris", Position = "QB", Team = "SEA" });
            collection.Insert(new Player { Id = 138, Name = "Helu Jr., Roy", Position = "RB", Team = "WAS" });
            collection.Insert(new Player { Id = 139, Name = "Thomas, Mike", Position = "WR", Team = "JAC" });
            collection.Insert(new Player { Id = 140, Name = "Carlson, John", Position = "TE", Team = "SEA" });
            collection.Insert(new Player { Id = 141, Name = "Flynn, Matt", Position = "QB", Team = "GB" });
            collection.Insert(new Player { Id = 142, Name = "Bush, Michael", Position = "RB", Team = "OAK" });
            collection.Insert(new Player { Id = 143, Name = "Edwards, Braylon", Position = "WR", Team = "SF" });
            collection.Insert(new Player { Id = 144, Name = "Rudolph, Kyle", Position = "TE", Team = "MIN" });
            collection.Insert(new Player { Id = 145, Name = "Tebow, Tim", Position = "QB", Team = "DEN" });
            collection.Insert(new Player { Id = 146, Name = "Jacobs, Brandon", Position = "RB", Team = "NYG" });
            collection.Insert(new Player { Id = 147, Name = "Crabtree, Michael", Position = "WR", Team = "SF" });
            collection.Insert(new Player { Id = 148, Name = "Kendricks, Lance", Position = "TE", Team = "STL" });
            collection.Insert(new Player { Id = 149, Name = "Grossman, Rex", Position = "QB", Team = "WAS" });
            collection.Insert(new Player { Id = 150, Name = "Thomas, Daniel", Position = "RB", Team = "MIA" });
            collection.Insert(new Player { Id = 151, Name = "Williams, Mike", Position = "WR", Team = "SEA" });
            collection.Insert(new Player { Id = 152, Name = "Tamme, Jacob", Position = "TE", Team = "IND" });
            collection.Insert(new Player { Id = 153, Name = "Hanie, Caleb", Position = "QB", Team = "CHI" });
            collection.Insert(new Player { Id = 154, Name = "Hightower, Tim", Position = "RB", Team = "WAS" });
            collection.Insert(new Player { Id = 155, Name = "Garcon, Pierre", Position = "WR", Team = "IND" });
            collection.Insert(new Player { Id = 156, Name = "Housler, Rob", Position = "TE", Team = "ARI" });
            collection.Insert(new Player { Id = 157, Name = "Young, Vince", Position = "QB", Team = "PHI" });
            collection.Insert(new Player { Id = 158, Name = "Jones, Thomas", Position = "RB", Team = "KC" });
            collection.Insert(new Player { Id = 159, Name = "Bennett, Earl", Position = "WR", Team = "CHI" });
            collection.Insert(new Player { Id = 160, Name = "Scheffler, Tony", Position = "TE", Team = "DET" });
            collection.Insert(new Player { Id = 161, Name = "Whitehurst, Charlie", Position = "QB", Team = "SEA" });
            collection.Insert(new Player { Id = 162, Name = "Carter, Delone", Position = "RB", Team = "IND" });
            collection.Insert(new Player { Id = 163, Name = "Meachem, Robert", Position = "WR", Team = "NO" });
            collection.Insert(new Player { Id = 164, Name = "Scaife, Bo", Position = "TE", Team = "CIN" });
            collection.Insert(new Player { Id = 165, Name = "Locker, Jake", Position = "QB", Team = "TEN" });
            collection.Insert(new Player { Id = 166, Name = "Scott, Bernard", Position = "RB", Team = "CIN" });
            collection.Insert(new Player { Id = 167, Name = "Nelson, Jordy", Position = "WR", Team = "GB" });
            collection.Insert(new Player { Id = 168, Name = "Quinn, Richard", Position = "TE", Team = "DEN" });
            collection.Insert(new Player { Id = 169, Name = "Ponder, Christian", Position = "QB", Team = "MIN" });
            collection.Insert(new Player { Id = 170, Name = "Starks, James", Position = "RB", Team = "GB" });
            collection.Insert(new Player { Id = 171, Name = "Ford, Jacoby", Position = "WR", Team = "OAK" });
            collection.Insert(new Player { Id = 172, Name = "Kaepernick, Colin", Position = "QB", Team = "SF" });
            collection.Insert(new Player { Id = 173, Name = "Woodhead, Danny", Position = "RB", Team = "NE" });
            collection.Insert(new Player { Id = 174, Name = "Ward, Hines", Position = "WR", Team = "PIT" });
            collection.Insert(new Player { Id = 175, Name = "Clausen, Jimmy", Position = "QB", Team = "CAR" });
            collection.Insert(new Player { Id = 176, Name = "Addai, Joseph", Position = "RB", Team = "IND" });
            collection.Insert(new Player { Id = 177, Name = "Jones, James", Position = "WR", Team = "GB" });
            collection.Insert(new Player { Id = 178, Name = "Kaeding, Nate", Position = "K", Team = "SD" });
            collection.Insert(new Player { Id = 179, Name = "Webb, Joe", Position = "QB", Team = "MIN" });
            collection.Insert(new Player { Id = 180, Name = "Tomlinson, LaDainian", Position = "RB", Team = "NYJ" });
            collection.Insert(new Player { Id = 181, Name = "Breaston, Steve", Position = "WR", Team = "KC" });
            collection.Insert(new Player { Id = 182, Name = "Hartley, Garrett", Position = "K", Team = "NO" });
            collection.Insert(new Player { Id = 183, Name = "Moore, Matt", Position = "QB", Team = "MIA" });
            collection.Insert(new Player { Id = 184, Name = "Thomas, Pierre", Position = "RB", Team = "NO" });
            collection.Insert(new Player { Id = 185, Name = "Floyd, Malcom", Position = "WR", Team = "SD" });
            collection.Insert(new Player { Id = 186, Name = "Gostkowski, Stephen", Position = "K", Team = "NE" });
            collection.Insert(new Player { Id = 187, Name = "Stanton, Drew", Position = "QB", Team = "DET" });
            collection.Insert(new Player { Id = 188, Name = "Brown, Ronnie", Position = "RB", Team = "PHI" });
            collection.Insert(new Player { Id = 189, Name = "Amendola, Danny", Position = "WR", Team = "STL" });
            collection.Insert(new Player { Id = 190, Name = "Janikowski, Sebastian", Position = "K", Team = "OAK" });
            collection.Insert(new Player { Id = 191, Name = "Wallace, Seneca", Position = "QB", Team = "CLE" });
            collection.Insert(new Player { Id = 192, Name = "Ridley, Stevan", Position = "RB", Team = "NE" });
            collection.Insert(new Player { Id = 193, Name = "Little, Greg", Position = "WR", Team = "CLE" });
            collection.Insert(new Player { Id = 194, Name = "Crosby, Mason", Position = "K", Team = "GB" });
            collection.Insert(new Player { Id = 195, Name = "Hill, Shaun", Position = "QB", Team = "DET" });
            collection.Insert(new Player { Id = 196, Name = "Hardesty, Montario", Position = "RB", Team = "CLE" });
            collection.Insert(new Player { Id = 197, Name = "Green, A.J.", Position = "WR", Team = "CIN" });
            collection.Insert(new Player { Id = 198, Name = "Rackers, Neil", Position = "K", Team = "HOU" });
            collection.Insert(new Player { Id = 199, Name = "Palmer, Jordan", Position = "QB", Team = "CIN" });
            collection.Insert(new Player { Id = 200, Name = "Spiller, C.J.", Position = "RB", Team = "BUF" });
            collection.Insert(new Player { Id = 201, Name = "Alexander, Danario", Position = "WR", Team = "STL" });
            collection.Insert(new Player { Id = 202, Name = "Bryant, Matt", Position = "K", Team = "ATL" });
            collection.Insert(new Player { Id = 203, Name = "Thigpen, Tyler", Position = "QB", Team = "BUF" });
            collection.Insert(new Player { Id = 204, Name = "Snelling, Jason", Position = "RB", Team = "ATL" });
            collection.Insert(new Player { Id = 205, Name = "Burleson, Nate", Position = "WR", Team = "DET" });
            collection.Insert(new Player { Id = 206, Name = "Tynes, Lawrence", Position = "K", Team = "NYG" });
            collection.Insert(new Player { Id = 207, Name = "Leinart, Matt", Position = "QB", Team = "HOU" });
            collection.Insert(new Player { Id = 208, Name = "Forsett, Justin", Position = "RB", Team = "SEA" });
            collection.Insert(new Player { Id = 209, Name = "Knox, Johnny", Position = "WR", Team = "CHI" });
            collection.Insert(new Player { Id = 210, Name = "Henery, Alex", Position = "K", Team = "PHI" });
            collection.Insert(new Player { Id = 211, Name = "Jackson, Brandon", Position = "RB", Team = "CLE" });
            collection.Insert(new Player { Id = 212, Name = "Walter, Kevin", Position = "WR", Team = "HOU" });
            collection.Insert(new Player { Id = 213, Name = "Brown, Josh", Position = "K", Team = "STL" });
            collection.Insert(new Player { Id = 214, Name = "Vereen, Shane", Position = "RB", Team = "NE" });
            collection.Insert(new Player { Id = 215, Name = "Sims-Walker, Mike", Position = "WR", Team = "STL" });
            collection.Insert(new Player { Id = 216, Name = "Buehler, David", Position = "K", Team = "DAL" });
            collection.Insert(new Player { Id = 217, Name = "Murray, DeMarco", Position = "RB", Team = "DAL" });
            collection.Insert(new Player { Id = 218, Name = "Branch, Deion", Position = "WR", Team = "NE" });
            collection.Insert(new Player { Id = 219, Name = "Carpenter, Dan", Position = "K", Team = "MIA" });
            collection.Insert(new Player { Id = 220, Name = "New York Jets, ", Position = "DEF", Team = "NYJ" });
            collection.Insert(new Player { Id = 221, Name = "Jennings, Rashad", Position = "RB", Team = "JAC" });
            collection.Insert(new Player { Id = 222, Name = "Bess, Davone", Position = "WR", Team = "MIA" });
            collection.Insert(new Player { Id = 223, Name = "Cundiff, Billy", Position = "K", Team = "BAL" });
            collection.Insert(new Player { Id = 224, Name = "Green Bay Packers, ", Position = "DEF", Team = "GB" });
            collection.Insert(new Player { Id = 225, Name = "Harper, Jamie", Position = "RB", Team = "TEN" });
            collection.Insert(new Player { Id = 226, Name = "Avant, Jason", Position = "WR", Team = "PHI" });
            collection.Insert(new Player { Id = 227, Name = "Suisham, Shaun", Position = "K", Team = "PIT" });
            collection.Insert(new Player { Id = 228, Name = "Pittsburgh Steelers, ", Position = "DEF", Team = "PIT" });
            collection.Insert(new Player { Id = 229, Name = "Williams, Ricky", Position = "RB", Team = "BAL" });
            collection.Insert(new Player { Id = 230, Name = "Murphy, Louis", Position = "WR", Team = "OAK" });
            collection.Insert(new Player { Id = 231, Name = "Akers, David", Position = "K", Team = "SF" });
            collection.Insert(new Player { Id = 232, Name = "Baltimore Ravens, ", Position = "DEF", Team = "BAL" });
            collection.Insert(new Player { Id = 233, Name = "Tate, Ben", Position = "RB", Team = "HOU" });
            collection.Insert(new Player { Id = 234, Name = "Armstrong, Anthony", Position = "WR", Team = "WAS" });
            collection.Insert(new Player { Id = 235, Name = "Vinatieri, Adam", Position = "K", Team = "IND" });
            collection.Insert(new Player { Id = 236, Name = "Philadelphia Eagles, ", Position = "DEF", Team = "PHI" });
            collection.Insert(new Player { Id = 237, Name = "Ringer, Javon", Position = "RB", Team = "TEN" });
            collection.Insert(new Player { Id = 238, Name = "Roberts, Andre", Position = "WR", Team = "ARI" });
            collection.Insert(new Player { Id = 239, Name = "Bironas, Rob", Position = "K", Team = "TEN" });
            collection.Insert(new Player { Id = 240, Name = "New England Patriots, ", Position = "DEF", Team = "NE" });
            collection.Insert(new Player { Id = 241, Name = "Sproles, Darren", Position = "RB", Team = "NO" });
            collection.Insert(new Player { Id = 242, Name = "Baldwin, Jon", Position = "WR", Team = "KC" });
            collection.Insert(new Player { Id = 243, Name = "Barth, Connor", Position = "K", Team = "TB" });
            collection.Insert(new Player { Id = 244, Name = "New York Giants, ", Position = "DEF", Team = "NYG" });
            collection.Insert(new Player { Id = 245, Name = "Morris, Maurice", Position = "RB", Team = "DET" });
            collection.Insert(new Player { Id = 246, Name = "Driver, Donald", Position = "WR", Team = "GB" });
            collection.Insert(new Player { Id = 247, Name = "Folk, Nick", Position = "K", Team = "NYJ" });
            collection.Insert(new Player { Id = 248, Name = "San Diego Chargers, ", Position = "DEF", Team = "SD" });
            collection.Insert(new Player { Id = 249, Name = "Redman, Isaac", Position = "RB", Team = "PIT" });
            collection.Insert(new Player { Id = 250, Name = "Simpson, Jerome", Position = "WR", Team = "CIN" });
            collection.Insert(new Player { Id = 251, Name = "Gould, Robbie", Position = "K", Team = "CHI" });
            collection.Insert(new Player { Id = 252, Name = "Chicago Bears, ", Position = "DEF", Team = "CHI" });
            collection.Insert(new Player { Id = 253, Name = "Graham, Earnest", Position = "RB", Team = "TB" });
            collection.Insert(new Player { Id = 254, Name = "Evans, Lee", Position = "WR", Team = "BAL" });
            collection.Insert(new Player { Id = 255, Name = "Feely, Jay", Position = "K", Team = "ARI" });
            collection.Insert(new Player { Id = 256, Name = "Kansas City Chiefs, ", Position = "DEF", Team = "KC" });
            collection.Insert(new Player { Id = 257, Name = "Barber, Marion", Position = "RB", Team = "CHI" });
            collection.Insert(new Player { Id = 258, Name = "Hester, Devin", Position = "WR", Team = "CHI" });
            collection.Insert(new Player { Id = 259, Name = "Hanson, Jason", Position = "K", Team = "DET" });
            collection.Insert(new Player { Id = 260, Name = "New Orleans Saints, ", Position = "DEF", Team = "NO" });
            collection.Insert(new Player { Id = 261, Name = "Hunter, Kendall", Position = "RB", Team = "SF" });
            collection.Insert(new Player { Id = 262, Name = "Sanders, Emmanuel", Position = "WR", Team = "PIT" });
            collection.Insert(new Player { Id = 263, Name = "Succop, Ryan", Position = "K", Team = "KC" });
            collection.Insert(new Player { Id = 264, Name = "Miami Dolphins, ", Position = "DEF", Team = "MIA" });
            collection.Insert(new Player { Id = 265, Name = "Washington, Leon", Position = "RB", Team = "SEA" });
            collection.Insert(new Player { Id = 266, Name = "Gaffney, Jabar", Position = "WR", Team = "WAS" });
            collection.Insert(new Player { Id = 267, Name = "Prater, Matt", Position = "K", Team = "DEN" });
            collection.Insert(new Player { Id = 268, Name = "Tennessee Titans, ", Position = "DEF", Team = "TEN" });
            collection.Insert(new Player { Id = 269, Name = "Green, Alex", Position = "RB", Team = "GB" });
            collection.Insert(new Player { Id = 270, Name = "Moore, Denarius", Position = "WR", Team = "OAK" });
            collection.Insert(new Player { Id = 271, Name = "Longwell, Ryan", Position = "K", Team = "MIN" });
            collection.Insert(new Player { Id = 272, Name = "Arizona Cardinals, ", Position = "DEF", Team = "ARI" });
            collection.Insert(new Player { Id = 273, Name = "Ivory, Chris", Position = "RB", Team = "NO" });
            collection.Insert(new Player { Id = 274, Name = "Morgan, Josh", Position = "WR", Team = "SF" });
            collection.Insert(new Player { Id = 275, Name = "Mare, Olindo", Position = "K", Team = "CAR" });
            collection.Insert(new Player { Id = 276, Name = "Houston Texans, ", Position = "DEF", Team = "HOU" });
            collection.Insert(new Player { Id = 277, Name = "Goodson, Mike", Position = "RB", Team = "CAR" });
            collection.Insert(new Player { Id = 278, Name = "Caldwell, Andre", Position = "WR", Team = "CIN" });
            collection.Insert(new Player { Id = 279, Name = "Scobee, Josh", Position = "K", Team = "JAC" });
            collection.Insert(new Player { Id = 280, Name = "Dallas Cowboys, ", Position = "DEF", Team = "DAL" });
            collection.Insert(new Player { Id = 281, Name = "Williams, Cadillac", Position = "RB", Team = "STL" });
            collection.Insert(new Player { Id = 282, Name = "Mason, Derrick", Position = "WR", Team = "NYJ" });
            collection.Insert(new Player { Id = 283, Name = "Dawson, Phil", Position = "K", Team = "CLE" });
            collection.Insert(new Player { Id = 284, Name = "Detroit Lions, ", Position = "DEF", Team = "DET" });
            collection.Insert(new Player { Id = 285, Name = "Miller, Lonyae", Position = "RB", Team = "DAL" });
            collection.Insert(new Player { Id = 286, Name = "LaFell, Brandon", Position = "WR", Team = "CAR" });
            collection.Insert(new Player { Id = 287, Name = "Reed, Jeff", Position = "K", Team = "SEA" });
            collection.Insert(new Player { Id = 288, Name = "Atlanta Falcons, ", Position = "DEF", Team = "ATL" });
            collection.Insert(new Player { Id = 289, Name = "Rodgers, Jacquizz", Position = "RB", Team = "ATL" });
            collection.Insert(new Player { Id = 290, Name = "Smith, Steve", Position = "WR", Team = "PHI" });
            collection.Insert(new Player { Id = 291, Name = "Lindell, Rian", Position = "K", Team = "BUF" });
            collection.Insert(new Player { Id = 292, Name = "Cincinnati Bengals, ", Position = "DEF", Team = "CIN" });
            collection.Insert(new Player { Id = 293, Name = "Harrison, Jerome", Position = "RB", Team = "DET" });
            collection.Insert(new Player { Id = 294, Name = "Benn, Arrelious", Position = "WR", Team = "TB" });
            collection.Insert(new Player { Id = 295, Name = "Gano, Graham", Position = "K", Team = "WAS" });
            collection.Insert(new Player { Id = 296, Name = "Buffalo Bills, ", Position = "DEF", Team = "BUF" });
            collection.Insert(new Player { Id = 297, Name = "Ward, Derrick", Position = "RB", Team = "HOU" });
            collection.Insert(new Player { Id = 298, Name = "Briscoe, Dezmon", Position = "WR", Team = "TB" });
            collection.Insert(new Player { Id = 299, Name = "Nugent, Mike", Position = "K", Team = "CIN" });
            collection.Insert(new Player { Id = 300, Name = "San Francisco 49ers, ", Position = "DEF", Team = "SF" });
            collection.Insert(new Player { Id = 301, Name = "Hilliard, Lex", Position = "RB", Team = "MIA" });
            collection.Insert(new Player { Id = 302, Name = "Young, Titus", Position = "WR", Team = "DET" });
            collection.Insert(new Player { Id = 303, Name = "Barth, Connor", Position = "K", Team = "TB" });
            collection.Insert(new Player { Id = 304, Name = "Seattle Seahawks, ", Position = "DEF", Team = "SEA" });
            collection.Insert(new Player { Id = 305, Name = "Royster, Evan", Position = "RB", Team = "WAS" });
            collection.Insert(new Player { Id = 306, Name = "Shipley, Jordan", Position = "WR", Team = "CIN" });
            collection.Insert(new Player { Id = 307, Name = "Novak, Nick", Position = "K", Team = "NYJ" });
            collection.Insert(new Player { Id = 308, Name = "Indianapolis Colts, ", Position = "DEF", Team = "IND" });
            collection.Insert(new Player { Id = 309, Name = "Choice, Tashard", Position = "RB", Team = "DAL" });
            collection.Insert(new Player { Id = 310, Name = "Decker, Eric", Position = "WR", Team = "DEN" });
            collection.Insert(new Player { Id = 311, Name = "Carolina Panthers, ", Position = "DEF", Team = "CAR" });
            collection.Insert(new Player { Id = 312, Name = "Gerhart, Toby", Position = "RB", Team = "MIN" });
            collection.Insert(new Player { Id = 313, Name = "Washington, Nate", Position = "WR", Team = "TEN" });
            collection.Insert(new Player { Id = 314, Name = "St. Louis Rams, ", Position = "DEF", Team = "STL" });
            collection.Insert(new Player { Id = 315, Name = "Brown, Donald", Position = "RB", Team = "IND" });
            collection.Insert(new Player { Id = 316, Name = "Jones, Jacoby", Position = "WR", Team = "HOU" });
            collection.Insert(new Player { Id = 317, Name = "Jacksonville Jaguars, ", Position = "DEF", Team = "JAC" });
            collection.Insert(new Player { Id = 318, Name = "Taylor, Chester", Position = "RB", Team = "CHI" });
            collection.Insert(new Player { Id = 319, Name = "Sanzenbacher, Dane", Position = "WR", Team = "CHI" });
            collection.Insert(new Player { Id = 320, Name = "Tampa Bay Bucs, ", Position = "DEF", Team = "TB" });
            collection.Insert(new Player { Id = 321, Name = "Allen, Anthony", Position = "RB", Team = "BAL" });
            collection.Insert(new Player { Id = 322, Name = "Gonzalez, Anthony", Position = "WR", Team = "IND" });
            collection.Insert(new Player { Id = 323, Name = "Cleveland Browns, ", Position = "DEF", Team = "CLE" });
            collection.Insert(new Player { Id = 324, Name = "Karim, Deji", Position = "RB", Team = "JAC" });
            collection.Insert(new Player { Id = 325, Name = "Jones, Donald", Position = "WR", Team = "BUF" });
            collection.Insert(new Player { Id = 326, Name = "Minnesota Vikings, ", Position = "DEF", Team = "MIN" });
            collection.Insert(new Player { Id = 327, Name = "Ware, Danny", Position = "RB", Team = "NYG" });
            collection.Insert(new Player { Id = 328, Name = "Avery, Donnie", Position = "WR", Team = "STL" });
            collection.Insert(new Player { Id = 329, Name = "Denver Broncos, ", Position = "DEF", Team = "DEN" });
            collection.Insert(new Player { Id = 330, Name = "Powell, Bilal", Position = "RB", Team = "NYJ" });
            collection.Insert(new Player { Id = 331, Name = "Smith, Torrey", Position = "WR", Team = "BAL" });
            collection.Insert(new Player { Id = 332, Name = "Washington Redskins, ", Position = "DEF", Team = "WAS" });
            collection.Insert(new Player { Id = 333, Name = "Williams, Keiland", Position = "RB", Team = "WAS" });
            collection.Insert(new Player { Id = 334, Name = "Cobb, Randall", Position = "WR", Team = "GB" });
            collection.Insert(new Player { Id = 335, Name = "Oakland Raiders, ", Position = "DEF", Team = "OAK" });
            collection.Insert(new Player { Id = 336, Name = "Logan, Stefan", Position = "RB", Team = "DET" });
            collection.Insert(new Player { Id = 337, Name = "Parrish, Roscoe", Position = "WR", Team = "BUF" });
            collection.Insert(new Player { Id = 338, Name = "Dixon, Anthony", Position = "RB", Team = "SF" });
            collection.Insert(new Player { Id = 339, Name = "Tate, Golden", Position = "WR", Team = "SEA" });
            collection.Insert(new Player { Id = 340, Name = "Stevens-Howling, LaRod", Position = "RB", Team = "ARI" });
            collection.Insert(new Player { Id = 341, Name = "Cribbs, Josh", Position = "WR", Team = "CLE" });
            collection.Insert(new Player { Id = 342, Name = "James, Javarris", Position = "RB", Team = "IND" });
            collection.Insert(new Player { Id = 343, Name = "Tate, Brandon", Position = "WR", Team = "NE" });
            collection.Insert(new Player { Id = 344, Name = "Slaton, Steve", Position = "RB", Team = "HOU" });
            collection.Insert(new Player { Id = 345, Name = "Obomanu, Ben", Position = "WR", Team = "SEA" });
            collection.Insert(new Player { Id = 346, Name = "Norwood, Jerious", Position = "RB", Team = "STL" });
            collection.Insert(new Player { Id = 347, Name = "Schilens, Chaz", Position = "WR", Team = "OAK" });
            collection.Insert(new Player { Id = 348, Name = "Booker, Lorenzo", Position = "RB", Team = "MIN" });
            collection.Insert(new Player { Id = 349, Name = "Clayton, Mark", Position = "WR", Team = "" });
            collection.Insert(new Player { Id = 350, Name = "Royal, Eddie", Position = "WR", Team = "DEN" });
            collection.Insert(new Player { Id = 351, Name = "Massaquoi, Mohamed", Position = "WR", Team = "CLE" });
            collection.Insert(new Player { Id = 352, Name = "Doss, Tandon", Position = "WR", Team = "BAL" });



            var collection2 = database.GetCollection<Auction>(typeof(Auction).Name);
            collection2.RemoveAll();
            collection2.Insert(new Auction { Id = 1, Name = "EastSide" });

            var collection3 = database.GetCollection<Owner>(typeof(Owner).Name);
            collection3.RemoveAll();
            collection3.Insert(new Owner { AuctionId = 1, Id = 1, Name = "Sponge Bobs - Bob Gross" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 2, Name = "Prom Queens - Steve Hebert" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 3, Name = "Terminators - Dave Houghton" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 4, Name = "D-Jabs - Bill Benert" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 5, Name = "No More Scum - Tom Houghton" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 6, Name = "Spill Kings - Dave Timm" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 7, Name = "Sodbusters - Larry Fitzpatrick" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 8, Name = "Superstars - Steve Sheahan" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 9, Name = "Wolfpack - Wally Kelsey" });
            collection3.Insert(new Owner { AuctionId = 1, Id = 10, Name = "Zephyrs - Erik Metling" });

            var collection4 = database.GetCollection<Ranking>(typeof(Ranking).Name);
            collection4.RemoveAll();
            collection4.Insert(new Ranking { Id = 1, Name = "Fanball - 10 player" });

            var collection5 = database.GetCollection<RankingDetail>(typeof(RankingDetail).Name);
            collection5.RemoveAll();
            collection5.Insert(new RankingDetail { Id = 1, RankingId = 1, PlayerId = 1, Estimate = 23, Rank = 1 });
            collection5.Insert(new RankingDetail { Id = 2, RankingId = 1, PlayerId = 2, Estimate = 44, Rank = 1 });
            collection5.Insert(new RankingDetail { Id = 3, RankingId = 1, PlayerId = 3, Estimate = 29, Rank = 1 });
            collection5.Insert(new RankingDetail { Id = 4, RankingId = 1, PlayerId = 4, Estimate = 14, Rank = 1 });
            collection5.Insert(new RankingDetail { Id = 5, RankingId = 1, PlayerId = 5, Estimate = 22, Rank = 2 });
            collection5.Insert(new RankingDetail { Id = 6, RankingId = 1, PlayerId = 6, Estimate = 42, Rank = 2 });
            collection5.Insert(new RankingDetail { Id = 7, RankingId = 1, PlayerId = 7, Estimate = 29, Rank = 2 });
            collection5.Insert(new RankingDetail { Id = 8, RankingId = 1, PlayerId = 8, Estimate = 12, Rank = 2 });
            collection5.Insert(new RankingDetail { Id = 9, RankingId = 1, PlayerId = 9, Estimate = 19, Rank = 3 });
            collection5.Insert(new RankingDetail { Id = 10, RankingId = 1, PlayerId = 10, Estimate = 41, Rank = 3 });
            collection5.Insert(new RankingDetail { Id = 11, RankingId = 1, PlayerId = 11, Estimate = 29, Rank = 3 });
            collection5.Insert(new RankingDetail { Id = 12, RankingId = 1, PlayerId = 12, Estimate = 9, Rank = 3 });
            collection5.Insert(new RankingDetail { Id = 13, RankingId = 1, PlayerId = 13, Estimate = 18, Rank = 4 });
            collection5.Insert(new RankingDetail { Id = 14, RankingId = 1, PlayerId = 14, Estimate = 39, Rank = 4 });
            collection5.Insert(new RankingDetail { Id = 15, RankingId = 1, PlayerId = 15, Estimate = 28, Rank = 4 });
            collection5.Insert(new RankingDetail { Id = 16, RankingId = 1, PlayerId = 16, Estimate = 8, Rank = 4 });
            collection5.Insert(new RankingDetail { Id = 17, RankingId = 1, PlayerId = 17, Estimate = 17, Rank = 5 });
            collection5.Insert(new RankingDetail { Id = 18, RankingId = 1, PlayerId = 18, Estimate = 38, Rank = 5 });
            collection5.Insert(new RankingDetail { Id = 19, RankingId = 1, PlayerId = 19, Estimate = 24, Rank = 5 });
            collection5.Insert(new RankingDetail { Id = 20, RankingId = 1, PlayerId = 20, Estimate = 6, Rank = 5 });
            collection5.Insert(new RankingDetail { Id = 21, RankingId = 1, PlayerId = 21, Estimate = 14, Rank = 6 });
            collection5.Insert(new RankingDetail { Id = 22, RankingId = 1, PlayerId = 22, Estimate = 36, Rank = 6 });
            collection5.Insert(new RankingDetail { Id = 23, RankingId = 1, PlayerId = 23, Estimate = 23, Rank = 6 });
            collection5.Insert(new RankingDetail { Id = 24, RankingId = 1, PlayerId = 24, Estimate = 4, Rank = 6 });
            collection5.Insert(new RankingDetail { Id = 25, RankingId = 1, PlayerId = 25, Estimate = 11, Rank = 7 });
            collection5.Insert(new RankingDetail { Id = 26, RankingId = 1, PlayerId = 26, Estimate = 29, Rank = 7 });
            collection5.Insert(new RankingDetail { Id = 27, RankingId = 1, PlayerId = 27, Estimate = 22, Rank = 7 });
            collection5.Insert(new RankingDetail { Id = 28, RankingId = 1, PlayerId = 28, Estimate = 4, Rank = 7 });
            collection5.Insert(new RankingDetail { Id = 29, RankingId = 1, PlayerId = 29, Estimate = 11, Rank = 8 });
            collection5.Insert(new RankingDetail { Id = 30, RankingId = 1, PlayerId = 30, Estimate = 29, Rank = 8 });
            collection5.Insert(new RankingDetail { Id = 31, RankingId = 1, PlayerId = 31, Estimate = 21, Rank = 8 });
            collection5.Insert(new RankingDetail { Id = 32, RankingId = 1, PlayerId = 32, Estimate = 4, Rank = 8 });
            collection5.Insert(new RankingDetail { Id = 33, RankingId = 1, PlayerId = 33, Estimate = 10, Rank = 9 });
            collection5.Insert(new RankingDetail { Id = 34, RankingId = 1, PlayerId = 34, Estimate = 27, Rank = 9 });
            collection5.Insert(new RankingDetail { Id = 35, RankingId = 1, PlayerId = 35, Estimate = 20, Rank = 9 });
            collection5.Insert(new RankingDetail { Id = 36, RankingId = 1, PlayerId = 36, Estimate = 2, Rank = 9 });
            collection5.Insert(new RankingDetail { Id = 37, RankingId = 1, PlayerId = 37, Estimate = 9, Rank = 10 });
            collection5.Insert(new RankingDetail { Id = 38, RankingId = 1, PlayerId = 38, Estimate = 26, Rank = 10 });
            collection5.Insert(new RankingDetail { Id = 39, RankingId = 1, PlayerId = 39, Estimate = 18, Rank = 10 });
            collection5.Insert(new RankingDetail { Id = 40, RankingId = 1, PlayerId = 40, Estimate = 2, Rank = 10 });
            collection5.Insert(new RankingDetail { Id = 41, RankingId = 1, PlayerId = 41, Estimate = 8, Rank = 11 });
            collection5.Insert(new RankingDetail { Id = 42, RankingId = 1, PlayerId = 42, Estimate = 26, Rank = 11 });
            collection5.Insert(new RankingDetail { Id = 43, RankingId = 1, PlayerId = 43, Estimate = 17, Rank = 11 });
            collection5.Insert(new RankingDetail { Id = 44, RankingId = 1, PlayerId = 44, Estimate = 2, Rank = 11 });
            collection5.Insert(new RankingDetail { Id = 45, RankingId = 1, PlayerId = 45, Estimate = 6, Rank = 12 });
            collection5.Insert(new RankingDetail { Id = 46, RankingId = 1, PlayerId = 46, Estimate = 25, Rank = 12 });
            collection5.Insert(new RankingDetail { Id = 47, RankingId = 1, PlayerId = 47, Estimate = 17, Rank = 12 });
            collection5.Insert(new RankingDetail { Id = 48, RankingId = 1, PlayerId = 48, Estimate = 2, Rank = 12 });
            collection5.Insert(new RankingDetail { Id = 49, RankingId = 1, PlayerId = 49, Estimate = 6, Rank = 13 });
            collection5.Insert(new RankingDetail { Id = 50, RankingId = 1, PlayerId = 50, Estimate = 24, Rank = 13 });
            collection5.Insert(new RankingDetail { Id = 51, RankingId = 1, PlayerId = 51, Estimate = 17, Rank = 13 });
            collection5.Insert(new RankingDetail { Id = 52, RankingId = 1, PlayerId = 52, Estimate = 2, Rank = 13 });
            collection5.Insert(new RankingDetail { Id = 53, RankingId = 1, PlayerId = 53, Estimate = 6, Rank = 14 });
            collection5.Insert(new RankingDetail { Id = 54, RankingId = 1, PlayerId = 54, Estimate = 22, Rank = 14 });
            collection5.Insert(new RankingDetail { Id = 55, RankingId = 1, PlayerId = 55, Estimate = 16, Rank = 14 });
            collection5.Insert(new RankingDetail { Id = 56, RankingId = 1, PlayerId = 56, Estimate = 2, Rank = 14 });
            collection5.Insert(new RankingDetail { Id = 57, RankingId = 1, PlayerId = 57, Estimate = 5, Rank = 15 });
            collection5.Insert(new RankingDetail { Id = 58, RankingId = 1, PlayerId = 58, Estimate = 21, Rank = 15 });
            collection5.Insert(new RankingDetail { Id = 59, RankingId = 1, PlayerId = 59, Estimate = 16, Rank = 15 });
            collection5.Insert(new RankingDetail { Id = 60, RankingId = 1, PlayerId = 60, Estimate = 1, Rank = 15 });
            collection5.Insert(new RankingDetail { Id = 61, RankingId = 1, PlayerId = 61, Estimate = 4, Rank = 16 });
            collection5.Insert(new RankingDetail { Id = 62, RankingId = 1, PlayerId = 62, Estimate = 20, Rank = 16 });
            collection5.Insert(new RankingDetail { Id = 63, RankingId = 1, PlayerId = 63, Estimate = 15, Rank = 16 });
            collection5.Insert(new RankingDetail { Id = 64, RankingId = 1, PlayerId = 64, Estimate = 1, Rank = 16 });
            collection5.Insert(new RankingDetail { Id = 65, RankingId = 1, PlayerId = 65, Estimate = 3, Rank = 17 });
            collection5.Insert(new RankingDetail { Id = 66, RankingId = 1, PlayerId = 66, Estimate = 19, Rank = 17 });
            collection5.Insert(new RankingDetail { Id = 67, RankingId = 1, PlayerId = 67, Estimate = 15, Rank = 17 });
            collection5.Insert(new RankingDetail { Id = 68, RankingId = 1, PlayerId = 68, Estimate = 1, Rank = 17 });
            collection5.Insert(new RankingDetail { Id = 69, RankingId = 1, PlayerId = 69, Estimate = 3, Rank = 18 });
            collection5.Insert(new RankingDetail { Id = 70, RankingId = 1, PlayerId = 70, Estimate = 18, Rank = 18 });
            collection5.Insert(new RankingDetail { Id = 71, RankingId = 1, PlayerId = 71, Estimate = 14, Rank = 18 });
            collection5.Insert(new RankingDetail { Id = 72, RankingId = 1, PlayerId = 72, Estimate = 1, Rank = 18 });
            collection5.Insert(new RankingDetail { Id = 73, RankingId = 1, PlayerId = 73, Estimate = 3, Rank = 19 });
            collection5.Insert(new RankingDetail { Id = 74, RankingId = 1, PlayerId = 74, Estimate = 17, Rank = 19 });
            collection5.Insert(new RankingDetail { Id = 75, RankingId = 1, PlayerId = 75, Estimate = 14, Rank = 19 });
            collection5.Insert(new RankingDetail { Id = 76, RankingId = 1, PlayerId = 76, Estimate = 1, Rank = 19 });
            collection5.Insert(new RankingDetail { Id = 77, RankingId = 1, PlayerId = 77, Estimate = 2, Rank = 20 });
            collection5.Insert(new RankingDetail { Id = 78, RankingId = 1, PlayerId = 78, Estimate = 17, Rank = 20 });
            collection5.Insert(new RankingDetail { Id = 79, RankingId = 1, PlayerId = 79, Estimate = 13, Rank = 20 });
            collection5.Insert(new RankingDetail { Id = 80, RankingId = 1, PlayerId = 80, Estimate = 1, Rank = 20 });
            collection5.Insert(new RankingDetail { Id = 81, RankingId = 1, PlayerId = 81, Estimate = 2, Rank = 21 });
            collection5.Insert(new RankingDetail { Id = 82, RankingId = 1, PlayerId = 82, Estimate = 16, Rank = 21 });
            collection5.Insert(new RankingDetail { Id = 83, RankingId = 1, PlayerId = 83, Estimate = 13, Rank = 21 });
            collection5.Insert(new RankingDetail { Id = 84, RankingId = 1, PlayerId = 84, Estimate = 1, Rank = 21 });
            collection5.Insert(new RankingDetail { Id = 85, RankingId = 1, PlayerId = 85, Estimate = 1, Rank = 22 });
            collection5.Insert(new RankingDetail { Id = 86, RankingId = 1, PlayerId = 86, Estimate = 16, Rank = 22 });
            collection5.Insert(new RankingDetail { Id = 87, RankingId = 1, PlayerId = 87, Estimate = 11, Rank = 22 });
            collection5.Insert(new RankingDetail { Id = 88, RankingId = 1, PlayerId = 88, Estimate = 1, Rank = 22 });
            collection5.Insert(new RankingDetail { Id = 89, RankingId = 1, PlayerId = 89, Estimate = 1, Rank = 23 });
            collection5.Insert(new RankingDetail { Id = 90, RankingId = 1, PlayerId = 90, Estimate = 15, Rank = 23 });
            collection5.Insert(new RankingDetail { Id = 91, RankingId = 1, PlayerId = 91, Estimate = 11, Rank = 23 });
            collection5.Insert(new RankingDetail { Id = 92, RankingId = 1, PlayerId = 92, Estimate = 1, Rank = 23 });
            collection5.Insert(new RankingDetail { Id = 93, RankingId = 1, PlayerId = 93, Estimate = 1, Rank = 24 });
            collection5.Insert(new RankingDetail { Id = 94, RankingId = 1, PlayerId = 94, Estimate = 14, Rank = 24 });
            collection5.Insert(new RankingDetail { Id = 95, RankingId = 1, PlayerId = 95, Estimate = 10, Rank = 24 });
            collection5.Insert(new RankingDetail { Id = 96, RankingId = 1, PlayerId = 96, Estimate = 1, Rank = 24 });
            collection5.Insert(new RankingDetail { Id = 97, RankingId = 1, PlayerId = 97, Estimate = 1, Rank = 25 });
            collection5.Insert(new RankingDetail { Id = 98, RankingId = 1, PlayerId = 98, Estimate = 13, Rank = 25 });
            collection5.Insert(new RankingDetail { Id = 99, RankingId = 1, PlayerId = 99, Estimate = 10, Rank = 25 });
            collection5.Insert(new RankingDetail { Id = 100, RankingId = 1, PlayerId = 100, Estimate = 1, Rank = 25 });
            collection5.Insert(new RankingDetail { Id = 101, RankingId = 1, PlayerId = 101, Estimate = 1, Rank = 26 });
            collection5.Insert(new RankingDetail { Id = 102, RankingId = 1, PlayerId = 102, Estimate = 11, Rank = 26 });
            collection5.Insert(new RankingDetail { Id = 103, RankingId = 1, PlayerId = 103, Estimate = 9, Rank = 26 });
            collection5.Insert(new RankingDetail { Id = 104, RankingId = 1, PlayerId = 104, Estimate = 1, Rank = 26 });
            collection5.Insert(new RankingDetail { Id = 105, RankingId = 1, PlayerId = 105, Estimate = 1, Rank = 27 });
            collection5.Insert(new RankingDetail { Id = 106, RankingId = 1, PlayerId = 106, Estimate = 11, Rank = 27 });
            collection5.Insert(new RankingDetail { Id = 107, RankingId = 1, PlayerId = 107, Estimate = 9, Rank = 27 });
            collection5.Insert(new RankingDetail { Id = 108, RankingId = 1, PlayerId = 108, Estimate = 1, Rank = 27 });
            collection5.Insert(new RankingDetail { Id = 109, RankingId = 1, PlayerId = 109, Estimate = 1, Rank = 28 });
            collection5.Insert(new RankingDetail { Id = 110, RankingId = 1, PlayerId = 110, Estimate = 10, Rank = 28 });
            collection5.Insert(new RankingDetail { Id = 111, RankingId = 1, PlayerId = 111, Estimate = 8, Rank = 28 });
            collection5.Insert(new RankingDetail { Id = 112, RankingId = 1, PlayerId = 112, Estimate = 1, Rank = 28 });
            collection5.Insert(new RankingDetail { Id = 113, RankingId = 1, PlayerId = 113, Estimate = 1, Rank = 29 });
            collection5.Insert(new RankingDetail { Id = 114, RankingId = 1, PlayerId = 114, Estimate = 8, Rank = 29 });
            collection5.Insert(new RankingDetail { Id = 115, RankingId = 1, PlayerId = 115, Estimate = 8, Rank = 29 });
            collection5.Insert(new RankingDetail { Id = 116, RankingId = 1, PlayerId = 116, Estimate = 1, Rank = 29 });
            collection5.Insert(new RankingDetail { Id = 117, RankingId = 1, PlayerId = 117, Estimate = 1, Rank = 30 });
            collection5.Insert(new RankingDetail { Id = 118, RankingId = 1, PlayerId = 118, Estimate = 7, Rank = 30 });
            collection5.Insert(new RankingDetail { Id = 119, RankingId = 1, PlayerId = 119, Estimate = 8, Rank = 30 });
            collection5.Insert(new RankingDetail { Id = 120, RankingId = 1, PlayerId = 120, Estimate = 1, Rank = 30 });
            collection5.Insert(new RankingDetail { Id = 121, RankingId = 1, PlayerId = 121, Estimate = 1, Rank = 31 });
            collection5.Insert(new RankingDetail { Id = 122, RankingId = 1, PlayerId = 122, Estimate = 6, Rank = 31 });
            collection5.Insert(new RankingDetail { Id = 123, RankingId = 1, PlayerId = 123, Estimate = 8, Rank = 31 });
            collection5.Insert(new RankingDetail { Id = 124, RankingId = 1, PlayerId = 124, Estimate = 1, Rank = 31 });
            collection5.Insert(new RankingDetail { Id = 125, RankingId = 1, PlayerId = 125, Estimate = 1, Rank = 32 });
            collection5.Insert(new RankingDetail { Id = 126, RankingId = 1, PlayerId = 126, Estimate = 6, Rank = 32 });
            collection5.Insert(new RankingDetail { Id = 127, RankingId = 1, PlayerId = 127, Estimate = 7, Rank = 32 });
            collection5.Insert(new RankingDetail { Id = 128, RankingId = 1, PlayerId = 128, Estimate = 1, Rank = 32 });
            collection5.Insert(new RankingDetail { Id = 129, RankingId = 1, PlayerId = 129, Estimate = 1, Rank = 33 });
            collection5.Insert(new RankingDetail { Id = 130, RankingId = 1, PlayerId = 130, Estimate = 6, Rank = 33 });
            collection5.Insert(new RankingDetail { Id = 131, RankingId = 1, PlayerId = 131, Estimate = 7, Rank = 33 });
            collection5.Insert(new RankingDetail { Id = 132, RankingId = 1, PlayerId = 132, Estimate = 1, Rank = 33 });
            collection5.Insert(new RankingDetail { Id = 133, RankingId = 1, PlayerId = 133, Estimate = 1, Rank = 34 });
            collection5.Insert(new RankingDetail { Id = 134, RankingId = 1, PlayerId = 134, Estimate = 5, Rank = 34 });
            collection5.Insert(new RankingDetail { Id = 135, RankingId = 1, PlayerId = 135, Estimate = 5, Rank = 34 });
            collection5.Insert(new RankingDetail { Id = 136, RankingId = 1, PlayerId = 136, Estimate = 1, Rank = 34 });
            collection5.Insert(new RankingDetail { Id = 137, RankingId = 1, PlayerId = 137, Estimate = 1, Rank = 35 });
            collection5.Insert(new RankingDetail { Id = 138, RankingId = 1, PlayerId = 138, Estimate = 5, Rank = 35 });
            collection5.Insert(new RankingDetail { Id = 139, RankingId = 1, PlayerId = 139, Estimate = 5, Rank = 35 });
            collection5.Insert(new RankingDetail { Id = 140, RankingId = 1, PlayerId = 140, Estimate = 1, Rank = 35 });
            collection5.Insert(new RankingDetail { Id = 141, RankingId = 1, PlayerId = 141, Estimate = 1, Rank = 36 });
            collection5.Insert(new RankingDetail { Id = 142, RankingId = 1, PlayerId = 142, Estimate = 5, Rank = 36 });
            collection5.Insert(new RankingDetail { Id = 143, RankingId = 1, PlayerId = 143, Estimate = 4, Rank = 36 });
            collection5.Insert(new RankingDetail { Id = 144, RankingId = 1, PlayerId = 144, Estimate = 1, Rank = 36 });
            collection5.Insert(new RankingDetail { Id = 145, RankingId = 1, PlayerId = 145, Estimate = 1, Rank = 37 });
            collection5.Insert(new RankingDetail { Id = 146, RankingId = 1, PlayerId = 146, Estimate = 5, Rank = 37 });
            collection5.Insert(new RankingDetail { Id = 147, RankingId = 1, PlayerId = 147, Estimate = 3, Rank = 37 });
            collection5.Insert(new RankingDetail { Id = 148, RankingId = 1, PlayerId = 148, Estimate = 1, Rank = 37 });
            collection5.Insert(new RankingDetail { Id = 149, RankingId = 1, PlayerId = 149, Estimate = 1, Rank = 38 });
            collection5.Insert(new RankingDetail { Id = 150, RankingId = 1, PlayerId = 150, Estimate = 5, Rank = 38 });
            collection5.Insert(new RankingDetail { Id = 151, RankingId = 1, PlayerId = 151, Estimate = 3, Rank = 38 });
            collection5.Insert(new RankingDetail { Id = 152, RankingId = 1, PlayerId = 152, Estimate = 1, Rank = 38 });
            collection5.Insert(new RankingDetail { Id = 153, RankingId = 1, PlayerId = 153, Estimate = 1, Rank = 39 });
            collection5.Insert(new RankingDetail { Id = 154, RankingId = 1, PlayerId = 154, Estimate = 3, Rank = 39 });
            collection5.Insert(new RankingDetail { Id = 155, RankingId = 1, PlayerId = 155, Estimate = 3, Rank = 39 });
            collection5.Insert(new RankingDetail { Id = 156, RankingId = 1, PlayerId = 156, Estimate = 1, Rank = 39 });
            collection5.Insert(new RankingDetail { Id = 157, RankingId = 1, PlayerId = 157, Estimate = 1, Rank = 40 });
            collection5.Insert(new RankingDetail { Id = 158, RankingId = 1, PlayerId = 158, Estimate = 3, Rank = 40 });
            collection5.Insert(new RankingDetail { Id = 159, RankingId = 1, PlayerId = 159, Estimate = 3, Rank = 40 });
            collection5.Insert(new RankingDetail { Id = 160, RankingId = 1, PlayerId = 160, Estimate = 1, Rank = 40 });
            collection5.Insert(new RankingDetail { Id = 161, RankingId = 1, PlayerId = 161, Estimate = 1, Rank = 41 });
            collection5.Insert(new RankingDetail { Id = 162, RankingId = 1, PlayerId = 162, Estimate = 3, Rank = 41 });
            collection5.Insert(new RankingDetail { Id = 163, RankingId = 1, PlayerId = 163, Estimate = 3, Rank = 41 });
            collection5.Insert(new RankingDetail { Id = 164, RankingId = 1, PlayerId = 164, Estimate = 1, Rank = 41 });
            collection5.Insert(new RankingDetail { Id = 165, RankingId = 1, PlayerId = 165, Estimate = 1, Rank = 42 });
            collection5.Insert(new RankingDetail { Id = 166, RankingId = 1, PlayerId = 166, Estimate = 2, Rank = 42 });
            collection5.Insert(new RankingDetail { Id = 167, RankingId = 1, PlayerId = 167, Estimate = 2, Rank = 42 });
            collection5.Insert(new RankingDetail { Id = 168, RankingId = 1, PlayerId = 168, Estimate = 1, Rank = 42 });
            collection5.Insert(new RankingDetail { Id = 169, RankingId = 1, PlayerId = 169, Estimate = 1, Rank = 43 });
            collection5.Insert(new RankingDetail { Id = 170, RankingId = 1, PlayerId = 170, Estimate = 2, Rank = 43 });
            collection5.Insert(new RankingDetail { Id = 171, RankingId = 1, PlayerId = 171, Estimate = 2, Rank = 43 });
            collection5.Insert(new RankingDetail { Id = 172, RankingId = 1, PlayerId = 172, Estimate = 1, Rank = 44 });
            collection5.Insert(new RankingDetail { Id = 173, RankingId = 1, PlayerId = 173, Estimate = 2, Rank = 44 });
            collection5.Insert(new RankingDetail { Id = 174, RankingId = 1, PlayerId = 174, Estimate = 2, Rank = 44 });
            collection5.Insert(new RankingDetail { Id = 175, RankingId = 1, PlayerId = 175, Estimate = 1, Rank = 45 });
            collection5.Insert(new RankingDetail { Id = 176, RankingId = 1, PlayerId = 176, Estimate = 2, Rank = 45 });
            collection5.Insert(new RankingDetail { Id = 177, RankingId = 1, PlayerId = 177, Estimate = 2, Rank = 45 });
            collection5.Insert(new RankingDetail { Id = 178, RankingId = 1, PlayerId = 178, Estimate = 2, Rank = 1 });
            collection5.Insert(new RankingDetail { Id = 179, RankingId = 1, PlayerId = 179, Estimate = 1, Rank = 46 });
            collection5.Insert(new RankingDetail { Id = 180, RankingId = 1, PlayerId = 180, Estimate = 2, Rank = 46 });
            collection5.Insert(new RankingDetail { Id = 181, RankingId = 1, PlayerId = 181, Estimate = 2, Rank = 46 });
            collection5.Insert(new RankingDetail { Id = 182, RankingId = 1, PlayerId = 182, Estimate = 2, Rank = 2 });
            collection5.Insert(new RankingDetail { Id = 183, RankingId = 1, PlayerId = 183, Estimate = 1, Rank = 47 });
            collection5.Insert(new RankingDetail { Id = 184, RankingId = 1, PlayerId = 184, Estimate = 1, Rank = 47 });
            collection5.Insert(new RankingDetail { Id = 185, RankingId = 1, PlayerId = 185, Estimate = 1, Rank = 47 });
            collection5.Insert(new RankingDetail { Id = 186, RankingId = 1, PlayerId = 186, Estimate = 2, Rank = 3 });
            collection5.Insert(new RankingDetail { Id = 187, RankingId = 1, PlayerId = 187, Estimate = 1, Rank = 48 });
            collection5.Insert(new RankingDetail { Id = 188, RankingId = 1, PlayerId = 188, Estimate = 1, Rank = 48 });
            collection5.Insert(new RankingDetail { Id = 189, RankingId = 1, PlayerId = 189, Estimate = 1, Rank = 48 });
            collection5.Insert(new RankingDetail { Id = 190, RankingId = 1, PlayerId = 190, Estimate = 2, Rank = 4 });
            collection5.Insert(new RankingDetail { Id = 191, RankingId = 1, PlayerId = 191, Estimate = 1, Rank = 49 });
            collection5.Insert(new RankingDetail { Id = 192, RankingId = 1, PlayerId = 192, Estimate = 1, Rank = 49 });
            collection5.Insert(new RankingDetail { Id = 193, RankingId = 1, PlayerId = 193, Estimate = 1, Rank = 49 });
            collection5.Insert(new RankingDetail { Id = 194, RankingId = 1, PlayerId = 194, Estimate = 2, Rank = 5 });
            collection5.Insert(new RankingDetail { Id = 195, RankingId = 1, PlayerId = 195, Estimate = 1, Rank = 50 });
            collection5.Insert(new RankingDetail { Id = 196, RankingId = 1, PlayerId = 196, Estimate = 1, Rank = 50 });
            collection5.Insert(new RankingDetail { Id = 197, RankingId = 1, PlayerId = 197, Estimate = 1, Rank = 50 });
            collection5.Insert(new RankingDetail { Id = 198, RankingId = 1, PlayerId = 198, Estimate = 1, Rank = 6 });
            collection5.Insert(new RankingDetail { Id = 199, RankingId = 1, PlayerId = 199, Estimate = 1, Rank = 51 });
            collection5.Insert(new RankingDetail { Id = 200, RankingId = 1, PlayerId = 200, Estimate = 1, Rank = 51 });
            collection5.Insert(new RankingDetail { Id = 201, RankingId = 1, PlayerId = 201, Estimate = 1, Rank = 51 });
            collection5.Insert(new RankingDetail { Id = 202, RankingId = 1, PlayerId = 202, Estimate = 1, Rank = 7 });
            collection5.Insert(new RankingDetail { Id = 203, RankingId = 1, PlayerId = 203, Estimate = 1, Rank = 52 });
            collection5.Insert(new RankingDetail { Id = 204, RankingId = 1, PlayerId = 204, Estimate = 1, Rank = 52 });
            collection5.Insert(new RankingDetail { Id = 205, RankingId = 1, PlayerId = 205, Estimate = 1, Rank = 52 });
            collection5.Insert(new RankingDetail { Id = 206, RankingId = 1, PlayerId = 206, Estimate = 1, Rank = 8 });
            collection5.Insert(new RankingDetail { Id = 207, RankingId = 1, PlayerId = 207, Estimate = 1, Rank = 53 });
            collection5.Insert(new RankingDetail { Id = 208, RankingId = 1, PlayerId = 208, Estimate = 1, Rank = 53 });
            collection5.Insert(new RankingDetail { Id = 209, RankingId = 1, PlayerId = 209, Estimate = 1, Rank = 53 });
            collection5.Insert(new RankingDetail { Id = 210, RankingId = 1, PlayerId = 210, Estimate = 1, Rank = 9 });
            collection5.Insert(new RankingDetail { Id = 211, RankingId = 1, PlayerId = 211, Estimate = 1, Rank = 54 });
            collection5.Insert(new RankingDetail { Id = 212, RankingId = 1, PlayerId = 212, Estimate = 1, Rank = 54 });
            collection5.Insert(new RankingDetail { Id = 213, RankingId = 1, PlayerId = 213, Estimate = 1, Rank = 10 });
            collection5.Insert(new RankingDetail { Id = 214, RankingId = 1, PlayerId = 214, Estimate = 1, Rank = 55 });
            collection5.Insert(new RankingDetail { Id = 215, RankingId = 1, PlayerId = 215, Estimate = 1, Rank = 55 });
            collection5.Insert(new RankingDetail { Id = 216, RankingId = 1, PlayerId = 216, Estimate = 1, Rank = 11 });
            collection5.Insert(new RankingDetail { Id = 217, RankingId = 1, PlayerId = 217, Estimate = 1, Rank = 56 });
            collection5.Insert(new RankingDetail { Id = 218, RankingId = 1, PlayerId = 218, Estimate = 1, Rank = 56 });
            collection5.Insert(new RankingDetail { Id = 219, RankingId = 1, PlayerId = 219, Estimate = 1, Rank = 12 });
            collection5.Insert(new RankingDetail { Id = 220, RankingId = 1, PlayerId = 220, Estimate = 3, Rank = 1 });
            collection5.Insert(new RankingDetail { Id = 221, RankingId = 1, PlayerId = 221, Estimate = 1, Rank = 57 });
            collection5.Insert(new RankingDetail { Id = 222, RankingId = 1, PlayerId = 222, Estimate = 1, Rank = 57 });
            collection5.Insert(new RankingDetail { Id = 223, RankingId = 1, PlayerId = 223, Estimate = 1, Rank = 13 });
            collection5.Insert(new RankingDetail { Id = 224, RankingId = 1, PlayerId = 224, Estimate = 3, Rank = 2 });
            collection5.Insert(new RankingDetail { Id = 225, RankingId = 1, PlayerId = 225, Estimate = 1, Rank = 58 });
            collection5.Insert(new RankingDetail { Id = 226, RankingId = 1, PlayerId = 226, Estimate = 1, Rank = 58 });
            collection5.Insert(new RankingDetail { Id = 227, RankingId = 1, PlayerId = 227, Estimate = 1, Rank = 14 });
            collection5.Insert(new RankingDetail { Id = 228, RankingId = 1, PlayerId = 228, Estimate = 3, Rank = 3 });
            collection5.Insert(new RankingDetail { Id = 229, RankingId = 1, PlayerId = 229, Estimate = 1, Rank = 59 });
            collection5.Insert(new RankingDetail { Id = 230, RankingId = 1, PlayerId = 230, Estimate = 1, Rank = 59 });
            collection5.Insert(new RankingDetail { Id = 231, RankingId = 1, PlayerId = 231, Estimate = 1, Rank = 15 });
            collection5.Insert(new RankingDetail { Id = 232, RankingId = 1, PlayerId = 232, Estimate = 3, Rank = 4 });
            collection5.Insert(new RankingDetail { Id = 233, RankingId = 1, PlayerId = 233, Estimate = 1, Rank = 60 });
            collection5.Insert(new RankingDetail { Id = 234, RankingId = 1, PlayerId = 234, Estimate = 1, Rank = 60 });
            collection5.Insert(new RankingDetail { Id = 235, RankingId = 1, PlayerId = 235, Estimate = 1, Rank = 16 });
            collection5.Insert(new RankingDetail { Id = 236, RankingId = 1, PlayerId = 236, Estimate = 3, Rank = 5 });
            collection5.Insert(new RankingDetail { Id = 237, RankingId = 1, PlayerId = 237, Estimate = 1, Rank = 61 });
            collection5.Insert(new RankingDetail { Id = 238, RankingId = 1, PlayerId = 238, Estimate = 1, Rank = 61 });
            collection5.Insert(new RankingDetail { Id = 239, RankingId = 1, PlayerId = 239, Estimate = 1, Rank = 17 });
            collection5.Insert(new RankingDetail { Id = 240, RankingId = 1, PlayerId = 240, Estimate = 2, Rank = 6 });
            collection5.Insert(new RankingDetail { Id = 241, RankingId = 1, PlayerId = 241, Estimate = 1, Rank = 62 });
            collection5.Insert(new RankingDetail { Id = 242, RankingId = 1, PlayerId = 242, Estimate = 1, Rank = 62 });
            collection5.Insert(new RankingDetail { Id = 243, RankingId = 1, PlayerId = 243, Estimate = 1, Rank = 18 });
            collection5.Insert(new RankingDetail { Id = 244, RankingId = 1, PlayerId = 244, Estimate = 2, Rank = 7 });
            collection5.Insert(new RankingDetail { Id = 245, RankingId = 1, PlayerId = 245, Estimate = 1, Rank = 63 });
            collection5.Insert(new RankingDetail { Id = 246, RankingId = 1, PlayerId = 246, Estimate = 1, Rank = 63 });
            collection5.Insert(new RankingDetail { Id = 247, RankingId = 1, PlayerId = 247, Estimate = 1, Rank = 19 });
            collection5.Insert(new RankingDetail { Id = 248, RankingId = 1, PlayerId = 248, Estimate = 2, Rank = 8 });
            collection5.Insert(new RankingDetail { Id = 249, RankingId = 1, PlayerId = 249, Estimate = 1, Rank = 64 });
            collection5.Insert(new RankingDetail { Id = 250, RankingId = 1, PlayerId = 250, Estimate = 1, Rank = 64 });
            collection5.Insert(new RankingDetail { Id = 251, RankingId = 1, PlayerId = 251, Estimate = 1, Rank = 20 });
            collection5.Insert(new RankingDetail { Id = 252, RankingId = 1, PlayerId = 252, Estimate = 2, Rank = 9 });
            collection5.Insert(new RankingDetail { Id = 253, RankingId = 1, PlayerId = 253, Estimate = 1, Rank = 65 });
            collection5.Insert(new RankingDetail { Id = 254, RankingId = 1, PlayerId = 254, Estimate = 1, Rank = 65 });
            collection5.Insert(new RankingDetail { Id = 255, RankingId = 1, PlayerId = 255, Estimate = 1, Rank = 21 });
            collection5.Insert(new RankingDetail { Id = 256, RankingId = 1, PlayerId = 256, Estimate = 1, Rank = 10 });
            collection5.Insert(new RankingDetail { Id = 257, RankingId = 1, PlayerId = 257, Estimate = 1, Rank = 66 });
            collection5.Insert(new RankingDetail { Id = 258, RankingId = 1, PlayerId = 258, Estimate = 1, Rank = 66 });
            collection5.Insert(new RankingDetail { Id = 259, RankingId = 1, PlayerId = 259, Estimate = 1, Rank = 22 });
            collection5.Insert(new RankingDetail { Id = 260, RankingId = 1, PlayerId = 260, Estimate = 1, Rank = 11 });
            collection5.Insert(new RankingDetail { Id = 261, RankingId = 1, PlayerId = 261, Estimate = 1, Rank = 67 });
            collection5.Insert(new RankingDetail { Id = 262, RankingId = 1, PlayerId = 262, Estimate = 1, Rank = 67 });
            collection5.Insert(new RankingDetail { Id = 263, RankingId = 1, PlayerId = 263, Estimate = 1, Rank = 23 });
            collection5.Insert(new RankingDetail { Id = 264, RankingId = 1, PlayerId = 264, Estimate = 1, Rank = 12 });
            collection5.Insert(new RankingDetail { Id = 265, RankingId = 1, PlayerId = 265, Estimate = 1, Rank = 68 });
            collection5.Insert(new RankingDetail { Id = 266, RankingId = 1, PlayerId = 266, Estimate = 1, Rank = 68 });
            collection5.Insert(new RankingDetail { Id = 267, RankingId = 1, PlayerId = 267, Estimate = 1, Rank = 24 });
            collection5.Insert(new RankingDetail { Id = 268, RankingId = 1, PlayerId = 268, Estimate = 1, Rank = 13 });
            collection5.Insert(new RankingDetail { Id = 269, RankingId = 1, PlayerId = 269, Estimate = 1, Rank = 69 });
            collection5.Insert(new RankingDetail { Id = 270, RankingId = 1, PlayerId = 270, Estimate = 1, Rank = 69 });
            collection5.Insert(new RankingDetail { Id = 271, RankingId = 1, PlayerId = 271, Estimate = 1, Rank = 25 });
            collection5.Insert(new RankingDetail { Id = 272, RankingId = 1, PlayerId = 272, Estimate = 1, Rank = 14 });
            collection5.Insert(new RankingDetail { Id = 273, RankingId = 1, PlayerId = 273, Estimate = 1, Rank = 70 });
            collection5.Insert(new RankingDetail { Id = 274, RankingId = 1, PlayerId = 274, Estimate = 1, Rank = 70 });
            collection5.Insert(new RankingDetail { Id = 275, RankingId = 1, PlayerId = 275, Estimate = 1, Rank = 26 });
            collection5.Insert(new RankingDetail { Id = 276, RankingId = 1, PlayerId = 276, Estimate = 1, Rank = 15 });
            collection5.Insert(new RankingDetail { Id = 277, RankingId = 1, PlayerId = 277, Estimate = 1, Rank = 71 });
            collection5.Insert(new RankingDetail { Id = 278, RankingId = 1, PlayerId = 278, Estimate = 1, Rank = 71 });
            collection5.Insert(new RankingDetail { Id = 279, RankingId = 1, PlayerId = 279, Estimate = 1, Rank = 27 });
            collection5.Insert(new RankingDetail { Id = 280, RankingId = 1, PlayerId = 280, Estimate = 1, Rank = 16 });
            collection5.Insert(new RankingDetail { Id = 281, RankingId = 1, PlayerId = 281, Estimate = 1, Rank = 72 });
            collection5.Insert(new RankingDetail { Id = 282, RankingId = 1, PlayerId = 282, Estimate = 1, Rank = 72 });
            collection5.Insert(new RankingDetail { Id = 283, RankingId = 1, PlayerId = 283, Estimate = 1, Rank = 28 });
            collection5.Insert(new RankingDetail { Id = 284, RankingId = 1, PlayerId = 284, Estimate = 1, Rank = 17 });
            collection5.Insert(new RankingDetail { Id = 285, RankingId = 1, PlayerId = 285, Estimate = 1, Rank = 73 });
            collection5.Insert(new RankingDetail { Id = 286, RankingId = 1, PlayerId = 286, Estimate = 1, Rank = 73 });
            collection5.Insert(new RankingDetail { Id = 287, RankingId = 1, PlayerId = 287, Estimate = 1, Rank = 29 });
            collection5.Insert(new RankingDetail { Id = 288, RankingId = 1, PlayerId = 288, Estimate = 1, Rank = 18 });
            collection5.Insert(new RankingDetail { Id = 289, RankingId = 1, PlayerId = 289, Estimate = 1, Rank = 74 });
            collection5.Insert(new RankingDetail { Id = 290, RankingId = 1, PlayerId = 290, Estimate = 1, Rank = 74 });
            collection5.Insert(new RankingDetail { Id = 291, RankingId = 1, PlayerId = 291, Estimate = 1, Rank = 30 });
            collection5.Insert(new RankingDetail { Id = 292, RankingId = 1, PlayerId = 292, Estimate = 1, Rank = 19 });
            collection5.Insert(new RankingDetail { Id = 293, RankingId = 1, PlayerId = 293, Estimate = 1, Rank = 75 });
            collection5.Insert(new RankingDetail { Id = 294, RankingId = 1, PlayerId = 294, Estimate = 1, Rank = 75 });
            collection5.Insert(new RankingDetail { Id = 295, RankingId = 1, PlayerId = 295, Estimate = 1, Rank = 31 });
            collection5.Insert(new RankingDetail { Id = 296, RankingId = 1, PlayerId = 296, Estimate = 1, Rank = 20 });
            collection5.Insert(new RankingDetail { Id = 297, RankingId = 1, PlayerId = 297, Estimate = 1, Rank = 76 });
            collection5.Insert(new RankingDetail { Id = 298, RankingId = 1, PlayerId = 298, Estimate = 1, Rank = 76 });
            collection5.Insert(new RankingDetail { Id = 299, RankingId = 1, PlayerId = 299, Estimate = 1, Rank = 32 });
            collection5.Insert(new RankingDetail { Id = 300, RankingId = 1, PlayerId = 300, Estimate = 1, Rank = 21 });
            collection5.Insert(new RankingDetail { Id = 301, RankingId = 1, PlayerId = 301, Estimate = 1, Rank = 77 });
            collection5.Insert(new RankingDetail { Id = 302, RankingId = 1, PlayerId = 302, Estimate = 1, Rank = 77 });
            collection5.Insert(new RankingDetail { Id = 303, RankingId = 1, PlayerId = 303, Estimate = 1, Rank = 33 });
            collection5.Insert(new RankingDetail { Id = 304, RankingId = 1, PlayerId = 304, Estimate = 1, Rank = 22 });
            collection5.Insert(new RankingDetail { Id = 305, RankingId = 1, PlayerId = 305, Estimate = 1, Rank = 78 });
            collection5.Insert(new RankingDetail { Id = 306, RankingId = 1, PlayerId = 306, Estimate = 1, Rank = 78 });
            collection5.Insert(new RankingDetail { Id = 307, RankingId = 1, PlayerId = 307, Estimate = 1, Rank = 34 });
            collection5.Insert(new RankingDetail { Id = 308, RankingId = 1, PlayerId = 308, Estimate = 1, Rank = 23 });
            collection5.Insert(new RankingDetail { Id = 309, RankingId = 1, PlayerId = 309, Estimate = 1, Rank = 79 });
            collection5.Insert(new RankingDetail { Id = 310, RankingId = 1, PlayerId = 310, Estimate = 1, Rank = 79 });
            collection5.Insert(new RankingDetail { Id = 311, RankingId = 1, PlayerId = 311, Estimate = 1, Rank = 24 });
            collection5.Insert(new RankingDetail { Id = 312, RankingId = 1, PlayerId = 312, Estimate = 1, Rank = 80 });
            collection5.Insert(new RankingDetail { Id = 313, RankingId = 1, PlayerId = 313, Estimate = 1, Rank = 80 });
            collection5.Insert(new RankingDetail { Id = 314, RankingId = 1, PlayerId = 314, Estimate = 1, Rank = 25 });
            collection5.Insert(new RankingDetail { Id = 315, RankingId = 1, PlayerId = 315, Estimate = 1, Rank = 81 });
            collection5.Insert(new RankingDetail { Id = 316, RankingId = 1, PlayerId = 316, Estimate = 1, Rank = 81 });
            collection5.Insert(new RankingDetail { Id = 317, RankingId = 1, PlayerId = 317, Estimate = 1, Rank = 26 });
            collection5.Insert(new RankingDetail { Id = 318, RankingId = 1, PlayerId = 318, Estimate = 1, Rank = 82 });
            collection5.Insert(new RankingDetail { Id = 319, RankingId = 1, PlayerId = 319, Estimate = 1, Rank = 82 });
            collection5.Insert(new RankingDetail { Id = 320, RankingId = 1, PlayerId = 320, Estimate = 1, Rank = 27 });
            collection5.Insert(new RankingDetail { Id = 321, RankingId = 1, PlayerId = 321, Estimate = 1, Rank = 83 });
            collection5.Insert(new RankingDetail { Id = 322, RankingId = 1, PlayerId = 322, Estimate = 1, Rank = 83 });
            collection5.Insert(new RankingDetail { Id = 323, RankingId = 1, PlayerId = 323, Estimate = 1, Rank = 28 });
            collection5.Insert(new RankingDetail { Id = 324, RankingId = 1, PlayerId = 324, Estimate = 1, Rank = 84 });
            collection5.Insert(new RankingDetail { Id = 325, RankingId = 1, PlayerId = 325, Estimate = 1, Rank = 84 });
            collection5.Insert(new RankingDetail { Id = 326, RankingId = 1, PlayerId = 326, Estimate = 1, Rank = 29 });
            collection5.Insert(new RankingDetail { Id = 327, RankingId = 1, PlayerId = 327, Estimate = 1, Rank = 85 });
            collection5.Insert(new RankingDetail { Id = 328, RankingId = 1, PlayerId = 328, Estimate = 1, Rank = 85 });
            collection5.Insert(new RankingDetail { Id = 329, RankingId = 1, PlayerId = 329, Estimate = 1, Rank = 30 });
            collection5.Insert(new RankingDetail { Id = 330, RankingId = 1, PlayerId = 330, Estimate = 1, Rank = 86 });
            collection5.Insert(new RankingDetail { Id = 331, RankingId = 1, PlayerId = 331, Estimate = 1, Rank = 86 });
            collection5.Insert(new RankingDetail { Id = 332, RankingId = 1, PlayerId = 332, Estimate = 1, Rank = 31 });
            collection5.Insert(new RankingDetail { Id = 333, RankingId = 1, PlayerId = 333, Estimate = 1, Rank = 87 });
            collection5.Insert(new RankingDetail { Id = 334, RankingId = 1, PlayerId = 334, Estimate = 1, Rank = 87 });
            collection5.Insert(new RankingDetail { Id = 335, RankingId = 1, PlayerId = 335, Estimate = 1, Rank = 32 });
            collection5.Insert(new RankingDetail { Id = 336, RankingId = 1, PlayerId = 336, Estimate = 1, Rank = 88 });
            collection5.Insert(new RankingDetail { Id = 337, RankingId = 1, PlayerId = 337, Estimate = 1, Rank = 88 });
            collection5.Insert(new RankingDetail { Id = 338, RankingId = 1, PlayerId = 338, Estimate = 1, Rank = 89 });
            collection5.Insert(new RankingDetail { Id = 339, RankingId = 1, PlayerId = 339, Estimate = 1, Rank = 89 });
            collection5.Insert(new RankingDetail { Id = 340, RankingId = 1, PlayerId = 340, Estimate = 1, Rank = 90 });
            collection5.Insert(new RankingDetail { Id = 341, RankingId = 1, PlayerId = 341, Estimate = 1, Rank = 90 });
            collection5.Insert(new RankingDetail { Id = 342, RankingId = 1, PlayerId = 342, Estimate = 1, Rank = 91 });
            collection5.Insert(new RankingDetail { Id = 343, RankingId = 1, PlayerId = 343, Estimate = 1, Rank = 91 });
            collection5.Insert(new RankingDetail { Id = 344, RankingId = 1, PlayerId = 344, Estimate = 1, Rank = 92 });
            collection5.Insert(new RankingDetail { Id = 345, RankingId = 1, PlayerId = 345, Estimate = 1, Rank = 92 });
            collection5.Insert(new RankingDetail { Id = 346, RankingId = 1, PlayerId = 346, Estimate = 1, Rank = 93 });
            collection5.Insert(new RankingDetail { Id = 347, RankingId = 1, PlayerId = 347, Estimate = 1, Rank = 93 });
            collection5.Insert(new RankingDetail { Id = 348, RankingId = 1, PlayerId = 348, Estimate = 1, Rank = 94 });
            collection5.Insert(new RankingDetail { Id = 349, RankingId = 1, PlayerId = 349, Estimate = 1, Rank = 94 });
            collection5.Insert(new RankingDetail { Id = 350, RankingId = 1, PlayerId = 350, Estimate = 1, Rank = 95 });
            collection5.Insert(new RankingDetail { Id = 351, RankingId = 1, PlayerId = 351, Estimate = 1, Rank = 96 });
            collection5.Insert(new RankingDetail { Id = 352, RankingId = 1, PlayerId = 352, Estimate = 1, Rank = 97 });


            var collection6 = database.GetCollection<BidDetail>(typeof(BidDetail).Name);
            collection6.RemoveAll();
            //collection6.Insert(new BidDetail { Id = 0, AuctionId = 1, PlayerId = 2, OwnerId = 5, BidAmount = 10 });
            //collection6.Insert(new BidDetail { Id = 1, AuctionId = 1, PlayerId = 5, OwnerId = 4, BidAmount = 5 });

        }
    }
}
